- .github/workflows/node.js.yml
- .gitignore
- .npmignore
- package-lock.json
- package.json
The build already failed before my changes. Could you look into that @CJ42
We should also update the dependencies, I'll take care of that in the next PR.
Should we ever decide to publish this via npm, everything is in place too.
> chore(build): provide build command and gh-actions

- contracts/TestHelpers/EIP712WithNonce.sol
- contracts/TestHelpers/NonceTestHelper.sol
- tests/NonceTestHelper.test.ts
> Multi Channel nonce for rc-0.1.4

- .github/workflows/build-and-test.yml
- .github/workflows/publish-ios-artifacts.yml
- .github/workflows/solhint.yml
- README.md
- java/build.gradle
`lsp-` prefix was added to repo name, this PR reflects these changes.
> chore: fix repo name

- make-ios.js
> build: Fix path in `make-ios.js`

- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateCore.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
Everything is mentioned in the commits
> refactor: quick fixes on LSP1, LSP7 and LSP8

- package-lock.json
- package.json
Upgrade dependency `@erc725/smart-contracts` to:
- use new feature in ERC725Utils library
- reduce package size and speed up CI 🚀
> feat: :pushpin: upgrade `@erc725/smart-contracts` to version 2.1.6

- .github/workflows/build-artifacts.yml
- .github/workflows/create-github-release.yml
- .github/workflows/publish-android-artifacts.yml
- .github/workflows/publish-ios-artifacts.yml
- .github/workflows/publish-npm-artifact.yml
Restructures release flow to build mobile artifacts before triggering release workflows.
> ci: upload artifacts from build workflow

- README.md
Fix instruction for Solidity Usage in README. 🩹 
(Previous instructions used Javascript syntax for imports). ❌
> docs: :bug: fix Solidity Usage section in README

- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/Handling/TokenAndVaultHandling.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/Handling/TokenHandling.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/LSP1UniversalReceiverDelegateVault.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
> fix: apply checks-effects-interactions pattern

- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- jest.setup.ts
- Change variable name from `universalReceiverAddress` to `universalReceiverDelegate`
> refactor: change variable name

- .prettierrc
- Increasing the `printWidth` for .sol files from 100 to 120.
> chore: increase printWidth in prettier

- .github/workflows/build-lint-test.yml
- package-lock.json
- package.json
Introduce multiple nom scripts to run tests for each LSPs and run these tests in separate jobs in CI.
> ci: run tests suites in parallel to increase CI speed

- contracts/Helpers/PayableContract.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/Factories/UniversalFactory.test.ts
- Fix linter warnings in `LSP6KeyManagerCore` and `Helpers` contracts (change tests accordingly)
> chore: fix linter warnings

- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/Handling/TokenAndVaultHandling.sol
- Remove address typecast in URD-UP
> refactor: remove address typecast in URD-UP

- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/Handling/TokenAndVaultHandling.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/Handling/TokenHandling.sol
- contracts/LSP5ReceivedAssets/LSP5Utils.sol
- Refactor on `LSP5Utils.sol` lib used in both URD - UP and Vault:
- Optimize typecasting variables
- Remove un-needed **SLOAD**
Gas optimized: **~2500**
> refactor: gas optimize LSP1UniversalReceiverDelegate

- contracts/LSP4DigitalAssetMetadata/LSP4DigitalAssetMetadata.sol
- contracts/LSP4DigitalAssetMetadata/LSP4DigitalAssetMetadataInitAbstract.sol
Revert #187 as tests fail for backward compatible version of LSP8
> revert: gas gulfing on LSP4

- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- package-lock.json
- package.json
> refactor: remove `Context` contract

- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/Handling/TokenHandling.sol
- Change variable names in LSP1-URD-Vault (by slither)
> chore: change variable names in LSP1-URD-Vault

- contracts/Factories/UniversalFactory.sol
- contracts/Helpers/FactoryTester.sol
- contracts/Helpers/ImplementationTester.sol
- tests/Factories/UniversalFactory.test.ts
- tests/utils/helpers.ts
- Resolve UniversalFactory failing tests.
**Todo**: Refactor UniversalFactory Tests (**Later**)
> test: resolve UniversalFactory failing tests

- .github/workflows/publish-ios-artifacts.yml
Updated final location of `UPContractsAbi.swift` is `Sources/UniversalProfile/UpContractsAbi.swift`.
> fix: updated final file path of the ABI file

- contracts/Factories/UniversalFactory.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/Factories/UniversalFactory.test.ts
- Remove ErrorHandler Lib and replace it with Address lib from OZ
> refactor: remove ErrorHandler Lib

- package-lock.json
- package.json
- build: upgrade @erc725-smart-contracts to `3.1.2`
> build: upgrade @erc725-smart-contracts to `3.1.2`

- package.json
> chore: fix wrong command in package.json

- contracts/LSP7DigitalAsset/LSP7DigitalAsset.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetInit.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetInitAbstract.sol
- contracts/LSP7DigitalAsset/presets/LSP7Mintable.sol
- contracts/LSP7DigitalAsset/presets/LSP7MintableInit.sol
- contracts/LSP7DigitalAsset/presets/LSP7MintableInitAbstract.sol
- Changing `isNFT` to `isNonDivisible`
> Change `isNFT` to `isNonDivisible`

- contracts/Helpers/UniversalReceivers/UniversalReceiverTester.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/LSP1UniversalReceiverDelegateVault.sol
- contracts/Legacy/UniversalReceiverAddressStore.sol
Hiding the linter error using solhint-disable.
> fix: Hide linter warnings

- contracts/LSP2ERC725YJSONSchema/LSP2Utils.sol
- contracts/LSP5ReceivedAssets/LSP5Utils.sol
- contracts/LSP6KeyManager/ILSP6KeyManager.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- LSP6KeyManagerCore.sol - “Unknow Error” should be “Unknown Error”
- LSP5Utils.sol - "elemnt" should be "element"
- ILSP6KeyManager.sol - _calldata -> payload
- LSP2Utils.sol - Not every function has NatSpec.
> docs: [Code Documentations] Update the smart contracts documentation

- contracts/Custom/ClaimOwnership.sol
Adjust variable style & visibility
> chore: adjust variable style & visibility

- contracts/Helpers/UniversalReceivers/UniversalReceiverDelegateRevert.sol
- tests/LSP7DigitalAsset/LSP7DigitalAsset.behaviour.ts
Testing of the transferOwnership feature for LSP7.
> test: add tests for transferOwnership on LSP7

- contracts/Helpers/UPWithInstantAcceptOwnership.sol
- contracts/Helpers/UniversalReceivers/UniversalReceiverDelegateRevert.sol
- contracts/Helpers/UniversalReceivers/UniversalReceiverDelegateTokenReentrant.sol
- contracts/Helpers/UniversalReceivers/UniversalReceiverDelegateVaultSetter.sol
- contracts/Helpers/UniversalReceivers/UniversalReceiverTester.sol
> chore: [WP-I21] Add comment in helper contracts to mark them for testing only

- constants.js
- contracts/LSP7DigitalAsset/ILSP7DigitalAsset.sol
- contracts/LSP7DigitalAsset/LSP7Constants.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/ILSP8IdentifiableDigitalAsset.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8Constants.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- tests/LSP7DigitalAsset/LSP7DigitalAsset.behaviour.ts
- tests/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.behaviour.ts
> refactor!: [WP-I19] Adding `bool[]` for token `transferBatch(..)`

- tests/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.behaviour.ts
> This PR is in draft. Awaiting for #373 to be merge to rebase on develop.
🧪 Add additional check in tests for LSP7CompatibleERC20 tests to ensure that the `universalReceiver(...)` function (LSP1 Hooks) is called with both the transfer functions from LSP7 and ERC20.
- `transfer(address,uint256)` from ERC20.
- `transferFrom(address,address,uint256)` from ERC20.
- `transfer(address,address,uint256,bool,bytes)` from LSP7.
> test: [WP-I18] LSP-7: LSP7CompatibleERC20 Compatibility to ERC20 regarding the hooks

- README.md
This is to fix the error with code coverage showing as 10 % before.
> docs: add again code coverage badge

- contracts/Helpers/ERC165Interfaces.sol
- contracts/Helpers/Reentrancy/BatchReentrancyRelayer.sol
- contracts/Helpers/Reentrancy/ReentrantContract.sol
- contracts/Helpers/Reentrancy/SingleReentrancyRelayer.sol
- contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
- contracts/LSP14Ownable2Step/LSP14Ownable2Step.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
In this PR the ILSP14Ownable2Step is created, to be used in other contracts.
> refactor: Create an interface for LSP14

- contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.sol
- contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20InitAbstract.sol
- contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20Mintable.sol
- contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20MintableInit.sol
- contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20MintableInitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721InitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8CompatibleERC721Mintable.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8CompatibleERC721MintableInit.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8CompatibleERC721MintableInitAbstract.sol
- hardhat.config.ts
> fix: upgrade to 0.8.15 for default compiler + increase minimum solc version for LSP7/LSP8 Compatible

- contracts/LSP16UniversalFactory/LSP16UniversalFactory.sol
> chore: [WP-D4] add documentation about LSP16 Edge cases

- contracts/LSP16UniversalFactory/LSP16UniversalFactory.sol
- contracts/Mocks/FallbackInitializer.sol
- tests/LSP16UniversalFactory/LSP16UniversalFactory.test.ts
- Apply Watchpug Recommendation
> refactor: [WP-I5] Allow initialization with empty Calldata in LSP16

- .all-contributorsrc
- CONTRIBUTING.md
- README.md
- package-lock.json
- package.json
This PR adds a list of contributors at the bottom of the `README`, using the `all-contributors-cli` package.
It also adds instructions on `CONTRIBUTE.md` to explain to external contributors how they can add themselves when making PRs.
-----
> chore: add contributors to the repository

- CHANGELOG.md
- package-lock.json
- package.json
revert old PR #316 to bump version from 0.7.0 to 0.8.0
> revert: prepare-release 0.8.0

- .github/workflows/benchmark.yml
- .github/workflows/build-artifacts.yml
- .github/workflows/build-lint-test.yml
- .github/workflows/coverage.yml
- .github/workflows/foundry-tests.yml
- .github/workflows/solc_version.yml
Edit the workflows so we have some jobs running on PRs to any branches.
> ci: run some jobs on any `pull_request`

- contracts/LSP10ReceivedVaults/LSP10Utils.sol
- contracts/LSP5ReceivedAssets/LSP5Utils.sol
In LSP5 and 10 Utils, refactor to place the check to fail first if the value under the LSP5[]/LSP10[] array is not `0x` or 16 bytes long.
👍 **Pro:**
Aim here is to improve code clarity + optimize runtime cost when receiving **additional assets**
This refactoring makes it less code and the logic a bit easier to read, as there is generic block of code to add a received asset/vault in the `dataKeys[]`.
👎 **Con:**
This increase the gas cost slightly for when received assets/vaults as follow:
- +393 gas when receiving the first asset (or setting from 0 to non zero).
- +6 gas when receiving any new assets
🔍 **Overview:**
The function is now 31 lines long as shown below:
> refactor: fail early in LSP5/10 to generate received assets/vaults

- tests/LSP20CallVerification/LSP6KeyManager/tests/Reentrancy/SingleExecuteToBatchExecute.test.ts
> test: resolve failing tests

- .github/workflows/benchmark.yml
- .github/workflows/solc_version.yml
- .prettierignore
- Add artifacts cache types to `.prettierignore`
- Make solc ci run only on solidity changes
- Remove not working settings in benchmark ci
> chore: adjust CI and prettier settings

- .github/PULL_REQUEST_TEMPLATE.md
> style: add Pull Request template

- package.json
Co-authored-by: Jean Cvllr <31145285+CJ42@users.noreply.github.com>
Fix exports for assets for 0.8.x
> fix: export assets for 0.8.1 (patch)

- tests/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.behaviour.ts
In LSP8 test suite, replace some `beforeEach` by `before` hooks to improve CI speed.
> test: replace `beforeEach` -> `before` hooks in LSP8

- contracts/LSP20CallVerification/LSP20Constants.sol
- contracts/LSP6KeyManager/LSP6Errors.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/LSP20CallVerification/LSP6/Interactions/Security.test.ts
- Make lsp20 functions callable by anyone without state changes
> refactor: make lsp20 functions callable by anyone without state changes

- CHANGELOG.md
- package.json
- Prepare Changelog
- Bump version of package.json
> chore: prepare 0.10.0 release

- README.md
Add example in README on how to important the constants in a Hardhat + Typescript based project.
> docs: add example to import constants in Hardhat Typescript projects

- CHANGELOG.md
- package-lock.json
- package.json
- Bump version in `package.json` from `0.10.0` --> `0.10.1`
- Prepare release `CHANGELOG.md`
> chore: prepare release 0.10.1

- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
Turn `_reentrancyStatus` into a internal variable
> feat!: change visibility of `_reentrancyStatus` state variable from `private` to `internal`

- .github/workflows/build-lint-test.yml
- package.json
- tests/LSP23MultiChainDeployment/LSP23MultiChainDeployment.behaviour.ts
- tests/LSP23MultiChainDeployment/LSP23MultiChainDeployment.test.ts
- fix lsp23 tests
- add tests to run with CI
> fix: failing tests for lsp23 + add LSP23 test suite in CI

- hardhat.config.ts
> await for PR #658 to be merged first.
- add LSP23 in the list of artifacts to be included in the npm package.
> build: add LSP23 in artifacts

- tests/LSP23MultiChainDeployment/LSP23MultiChainDeployment.test.ts
Main and develop were out of sync, this PR make them even again.
> chore: re sync main and develop

- .gitignore
- dodoc/config.ts
- dodoc/template.sqrl
- package-lock.json
- package.json
This PR updates the following things:
- `hardhat-dodoc` to `v0.3.11`.
- dodoc config with new helper function & `include`.
- dodoc template with specs link at the top.
> chore: update `hardhat-dodoc` & dodoc config & dodoc template

- slither.config.json
Add `slither.config.json` to enable team members or anyone cloning the repository to run slither locally from the CLI, without having to reset the slither configs every time.
> build: add slither config at root of repo

- contracts/LSP6KeyManager/ILSP6KeyManager.sol
- contracts/LSP6KeyManager/LSP6Errors.sol
- contracts/LSP6KeyManager/LSP6KeyManager.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP6KeyManager/LSP6KeyManagerInit.sol
- contracts/LSP6KeyManager/LSP6KeyManagerInitAbstract.sol
- docs/contracts/LSP6KeyManager/LSP6KeyManager.md
- dodoc/config.ts
Improve Natspec comments for `LSP6KeyManager` and its own modules + interfaces and add auto-generated docs.
> docs: improve LSP6 Natspec comments + add auto-generated docs

- contracts/LSP4DigitalAssetMetadata/LSP4DigitalAssetMetadata.sol
- contracts/LSP4DigitalAssetMetadata/LSP4DigitalAssetMetadataInitAbstract.sol
- contracts/LSP4DigitalAssetMetadata/LSP4Errors.sol
- docs/contracts/LSP4DigitalAssetMetadata/LSP4DigitalAssetMetadata.md
Improve Natspec comments for `LSP4DigitalAssetMetadata` and add auto-generated docs.
> docs: improve LSP4 Natspec comments + add auto-generated docs

- contracts/LSP7DigitalAsset/extensions/ILSP7CompatibleERC20.sol
- contracts/LSP7DigitalAsset/extensions/LSP7Burnable.sol
- contracts/LSP7DigitalAsset/extensions/LSP7BurnableInitAbstract.sol
- contracts/LSP7DigitalAsset/extensions/LSP7CappedSupply.sol
- contracts/LSP7DigitalAsset/extensions/LSP7CappedSupplyInitAbstract.sol
- contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.sol
- contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20InitAbstract.sol
- contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20Mintable.sol
- contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20MintableInit.sol
- contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20MintableInitAbstract.sol
- contracts/LSP7DigitalAsset/presets/LSP7Mintable.sol
- contracts/LSP7DigitalAsset/presets/LSP7MintableInit.sol
- contracts/LSP7DigitalAsset/presets/LSP7MintableInitAbstract.sol
- docs/contracts/LSP7DigitalAsset/extensions/LSP7Burnable.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CappedSupply.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20Mintable.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7Mintable.md
Improve Natspec comments for `LSP7DigitalAsset` --> `presets/` and `extensions/` folder.
> docs: improve LSP7 preset & extensions Natspec comments + add auto-generated docs

- contracts/LSP8IdentifiableDigitalAsset/ILSP8IdentifiableDigitalAsset.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetInitAbstract.sol
- docs/contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.md
Improve Natspec comments for `LSP8IdentifiableDigitalAsset` and add auto-generated docs.
> docs: improve LSP8 Natspec comments + add auto-generate docs

- contracts/LSP7DigitalAsset/extensions/ILSP7CompatibleERC20.sol
- contracts/LSP7DigitalAsset/extensions/LSP7CappedSupply.sol
- contracts/LSP7DigitalAsset/presets/LSP7MintableInitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/ILSP8CompatibleERC721.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Burnable.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CappedSupply.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CappedSupplyInitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721InitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Enumerable.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8EnumerableInitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8CompatibleERC721Mintable.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8CompatibleERC721MintableInit.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8CompatibleERC721MintableInitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8Mintable.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8MintableInit.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8MintableInitAbstract.sol
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Burnable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CappedSupply.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Enumerable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/presets/LSP8CompatibleERC721Mintable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/presets/LSP8Mintable.md
Improve Natspec comments for `LSP8IdentifiableDigitalAsset` --> `presets/` and `extensions/` folder + add auto-generated docs.
> docs: improve LSP8 preset & extensions Natspec comments + add auto-generated docs

- contracts/LSP0ERC725Account/ILSP0ERC725Account.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountInit.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountInitAbstract.sol
- contracts/LSP9Vault/ILSP9Vault.sol
- contracts/LSP9Vault/LSP9Errors.sol
- contracts/LSP9Vault/LSP9Vault.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- contracts/LSP9Vault/LSP9VaultInit.sol
- contracts/LSP9Vault/LSP9VaultInitAbstract.sol
- contracts/UniversalProfile.sol
- contracts/UniversalProfileInit.sol
- contracts/UniversalProfileInitAbstract.sol
- docs/contracts/LSP9Vault/LSP9Vault.md
- docs/contracts/UniversalProfile.md
This PR updates the Natspec of the LSP9 contracts. 
Additionally I cross-checked `LSP0` and `UniversalProfile` contracts with the `LSP9` contracts to have better Natspec documentation in all of them as they are very similar in terms of functionality, the difference being rather in the context which is described in each of them.
After updating all the Natspec documentation I generated the `.md` docs and pushed them.
> docs: update LSP9 Natspec

- contracts/LSP10ReceivedVaults/LSP10Utils.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/LSP1UniversalReceiverDelegateVault.sol
- contracts/LSP2ERC725YJSONSchema/LSP2Utils.sol
- contracts/LSP5ReceivedAssets/LSP5Utils.sol
- contracts/Mocks/GenericExecutorWithBalanceOfFunction.sol
- docs/contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.md
- docs/contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/LSP1UniversalReceiverDelegateVault.md
- docs/libraries/LSP10ReceivedVaults/LSP10Utils.md
- docs/libraries/LSP2ERC725YJSONSchema/LSP2Utils.md
- docs/libraries/LSP5ReceivedAssets/LSP5Utils.md
- tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP.behaviour.ts
- tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault.behaviour.ts
Allow the UP URD to return when it cannot update the `dataKeys`.
> refactor!: [C4#95] return when URD has no permission for UP

- CHANGELOG.md
Add missing details in CHANGELOG related to Code4Rena bug fixes + extra changes made before v0.11.0-rc.0
> docs: add Code4Rena bug fixes + missing details in CHANGELOG for v0.11.1

- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/LSP20CallVerification/LSP6/Admin/PermissionChangeOwner.test.ts
- tests/LSP6KeyManager/Admin/PermissionChangeOwner.test.ts
- tests/LSP6KeyManager/LSP6ControlledToken.test.ts
Add new path for `CHANGEOWNER` permission, the `renounceOwnership()` path.
> feat!: Add `renounceOwnership()` path through the LSP6

- contracts/Mocks/ERC165Interfaces.sol
- tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP.behaviour.ts
- tests/Mocks/ERC165Interfaces.test.ts
- fix tests of LSP1Delegate InterfaceId where it wasn't working as intended
> test: fix tests of LSP1Delegate InterfaceId

- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP17ContractExtension/LSP17Extension.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/LSP1UniversalReceiverDelegateVault.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- contracts/Version.sol
- docs/contracts/LSP0ERC725Account/LSP0ERC725Account.md
- docs/contracts/LSP17ContractExtension/LSP17Extension.md
- docs/contracts/LSP17Extensions/Extension4337.md
- docs/contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.md
- docs/contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/LSP1UniversalReceiverDelegateVault.md
- docs/contracts/LSP6KeyManager/LSP6KeyManager.md
- docs/contracts/LSP7DigitalAsset/LSP7DigitalAsset.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7Burnable.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CappedSupply.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20Mintable.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7Mintable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Burnable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CappedSupply.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Enumerable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/presets/LSP8CompatibleERC721Mintable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/presets/LSP8Mintable.md
- docs/contracts/LSP9Vault/LSP9Vault.md
- docs/contracts/UniversalProfile.md
This PR creates the `Version.sol` contract that allows to track the package version in which the contract was released.
> feat!: create `Version` contract and inherit it

- contracts/LSP23LinkedContractsFactory/modules/README.md
> fix: replaced broken LSP23 link

- .github/workflows/coverage.yml
> chore: re-sync main to release as 0.12.0

- contracts/LSP25ExecuteRelayCall/LSP25MultiChannelNonce.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> refactor: [I-01 + I-02] Update is valid nonce + remove iterator initialization

- contracts/LSP0ERC725Account/LSP0Constants.sol
- contracts/LSP9Vault/LSP9Constants.sol
- contracts/Mocks/LSP1TypeIDsTester.sol
- tests/Mocks/LSP1TypeIDs.test.ts
This PR introduces tests for LSP1 Type IDs hashes, so they are consistent in both javascript and solidity
> test: add tests for LSP1 Type IDs

- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/LSP1UniversalReceiverDelegateVault.sol
Re-use the code to check if the `notifier` is an EOA via `tx.origin` in the LSP1 Delegate contracts for UP and Vaults, using a `modifier`.
> refactor: use `modifier` to check if notifier is EOA or not

- constants.ts
Add missing conversion from hash/hashFunction to verificationData/verificationFunction.
> fix: Add hashFunction/hash to verificationFunction/verificationData to constants file

- docs/contracts/LSP0ERC725Account/LSP0ERC725Account.md
- docs/contracts/LSP25ExecuteRelayCall/LSP25MultiChannelNonce.md
- docs/contracts/LSP6KeyManager/LSP6KeyManager.md
- docs/contracts/LSP7DigitalAsset/LSP7DigitalAsset.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7Burnable.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CappedSupply.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20Mintable.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7Mintable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Burnable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CappedSupply.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Enumerable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/presets/LSP8CompatibleERC721Mintable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/presets/LSP8Mintable.md
- docs/contracts/LSP9Vault/LSP9Vault.md
- docs/contracts/UniversalProfile.md
- dodoc/config.ts
This PR allows for generating local links inside `@param` & `@return` tags.
> refactor: generate local links for `@param` & `@return`

- constants.ts
Refactor verification from (hash/hashFunction) verificationData/verficationFunction to
```js
{
verification?: {
method: string,
data: string,
source?: string,
}
}
```
> chore: Refactor verification

- docs/contracts/LSP0ERC725Account/LSP0ERC725Account.md
- docs/contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.md
- docs/contracts/LSP6KeyManager/LSP6KeyManager.md
- docs/contracts/LSP7DigitalAsset/LSP7DigitalAsset.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7Burnable.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CappedSupply.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20Mintable.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7Mintable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Burnable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CappedSupply.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Enumerable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/presets/LSP8CompatibleERC721Mintable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/presets/LSP8Mintable.md
- docs/contracts/LSP9Vault/LSP9Vault.md
- docs/contracts/UniversalProfile.md
- docs/libraries/LSP6KeyManager/LSP6Utils.md
- dodoc/config.ts
- dodoc/template.sqrl
- tsconfig.json
Allow generating local links in the following natspec tags:
- `@title`
- `@custom:...`
> refactor: fix auto-generated local links in dodoc

- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- docs/contracts/ERC725/ERC725.md
- docs/contracts/LSP0ERC725Account/LSP0ERC725Account.md
- docs/contracts/LSP9Vault/LSP9Vault.md
- docs/contracts/UniversalProfile.md
- package-lock.json
- package.json
update @erc725/smart-contracts 7.0.0
> chore: update @erc725/smart-contracts 7.0.0

- README.md
Fix the import example in the `README.md` file
> chore: update import example in `README.md`

- contracts/LSP16UniversalFactory/LSP16UniversalFactory.sol
- docs/contracts/LSP16UniversalFactory/LSP16UniversalFactory.md
Updates documentation based on feedback from https://github.com/lukso-network/docs/pull/792
All credit to @0xbasar 🕵️‍♂️
> docs: Update LSP16 description

- contracts/LSP16UniversalFactory/LSP16UniversalFactory.md
- contracts/LSP16UniversalFactory/LSP16UniversalFactory.sol
- docs/contracts/LSP16UniversalFactory/LSP16UniversalFactory.md
-Adjust LSP16 natspec and parameter name
> refactor: adjust LSP16 natspec and parameter name

- .github/workflows/benchmark.yml
> ci: revert changes related to Benchmark CI

- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
> fix: [L-07] move _beforeTokenTransfer before balance check

- constants.ts
Add `attributes` types to `LSP4` metadata.
> feat: Add types for attributes

- constants.ts
This little fix make `attributes` as optional based on the docs. I missed it in previous PR.
> fix: Make `attributes` optional

- constants.ts
> feat: Add contract asset type

- packages/lsp23-contracts/hardhat.config.ts
- packages/lsp4-contracts/hardhat.config.ts
- packages/lsp6-contracts/hardhat.config.ts
- packages/lsp7-contracts/hardhat.config.ts
- packages/lsp8-contracts/hardhat.config.ts
- packages/lsp9-contracts/hardhat.config.ts
- packages/universalprofile-contracts/hardhat.config.ts
Export artefacts in each package
> chore: export artifacts from each package

- .github/workflows/release.yml
- packages/lsp-smart-contracts/package.json
- packages/lsp0-contracts/package.json
- packages/lsp1delegate-contracts/package.json
- packages/lsp23-contracts/package.json
- packages/lsp4-contracts/package.json
- packages/lsp6-contracts/package.json
- packages/lsp7-contracts/package.json
- packages/lsp8-contracts/package.json
- packages/lsp9-contracts/package.json
- template/package.json
- turbo.json
Include typescript types in the npm package
> chore: include types in the npm package

- package.json
> chore: try resolve merge conflicts for `package.json` from `develop` to `main`

- .release-please-manifest.json
- **fix: Add release-please metadata to main**
> fix: Merge release-please manifest to main

- packages/lsp20-contracts/README.md
- packages/lsp25-contracts/README.md
- packages/universalprofile-contracts/README.md
Add some changes in the README of these packages to trigger release-please on merge to `main`.
> docs: add installation instruction in README of LSP20, 25 and UP packages

- packages/lsp4-contracts/constants.ts
> fix: add missing `name` field to LSP4 type

- foundry.toml
- package-lock.json
- packages/lsp-smart-contracts/contracts/LSP2ERC725YJSONSchema/LSP2Constants.sol
- packages/lsp-smart-contracts/contracts/LSP4DigitalAssetMetadata/LSP4Utils.sol
- packages/lsp-smart-contracts/hardhat.config.ts
- packages/lsp2-contracts/contracts/LSP2Constants.sol
- packages/lsp4-contracts/.solhint.json
- packages/lsp4-contracts/contracts/LSP4Utils.sol
- packages/lsp4-contracts/contracts/mock/LSP4MetadataTester.sol
- packages/lsp4-contracts/hardhat.config.ts
- packages/lsp4-contracts/package.json
- packages/lsp4-contracts/tests/LSP4MetadataTester.test.ts
This PR creates a solidity lib for LSP4 that allows to easier manage an on-chain json for LSP4Metadata
> feat: create `LSP4Utils.sol`

- .github/workflows/build-lint-test.yml
- packages/lsp-smart-contracts/tests/LSP23LinkedContractsDeployment/LSP23LinkedContractsDeployment.test.ts
- packages/lsp14-contracts/wagmi.config.ts
- packages/lsp16-contracts/wagmi.config.ts
- packages/lsp17-contracts/wagmi.config.ts
- packages/lsp17contractextension-contracts/wagmi.config.ts
- packages/lsp20-contracts/wagmi.config.ts
- packages/lsp25-contracts/wagmi.config.ts
- packages/universalprofile-contracts/wagmi.config.ts
> build: add missing wagmi config files in packages

- packages/lsp-smart-contracts/README.md
- packages/lsp0-contracts/README.md
- packages/lsp1-contracts/README.md
- packages/lsp10-contracts/README.md
- packages/lsp12-contracts/README.md
- packages/lsp14-contracts/README.md
- packages/lsp17-contracts/README.md
- packages/lsp17contractextension-contracts/README.md
- packages/lsp1delegate-contracts/README.md
- packages/lsp2-contracts/README.md
- packages/lsp20-contracts/README.md
- packages/lsp25-contracts/README.md
- packages/lsp3-contracts/README.md
- packages/lsp4-contracts/README.md
- packages/lsp5-contracts/README.md
- packages/lsp6-contracts/README.md
- packages/lsp7-contracts/README.md
- packages/lsp8-contracts/README.md
- packages/lsp9-contracts/README.md
- Add `Available Constants & Types` in each package
> chore: Add constants section in README of each package 

- packages/lsp3-contracts/constants.ts
- packages/lsp4-contracts/constants.ts
Add missing type for assets/avatars that point to contract.
> feat: add type for contract assets/avatar

- .github/workflows/benchmark.yml
- packages/lsp-smart-contracts/constants.ts
- packages/lsp-smart-contracts/contracts/Mocks/LSP1TypeIDsTester.sol
- packages/lsp7-contracts/constants.ts
- packages/lsp7-contracts/contracts/LSP7Constants.sol
- packages/lsp7-contracts/contracts/LSP7DigitalAssetInitAbstract.sol
- packages/lsp8-contracts/constants.ts
- packages/lsp8-contracts/contracts/LSP8Constants.sol
- packages/lsp8-contracts/contracts/Mocks/UniversalReceiver.sol
- packages/lsp8-contracts/contracts/extensions/LSP8Votes.sol
- packages/lsp8-contracts/contracts/extensions/LSP8VotesConstants.sol
- packages/lsp8-contracts/contracts/extensions/LSP8VotesInitAbstract.sol
- packages/lsp8-contracts/tests/LSP8Votes.test.ts
> feat: create LSP8VotesInitAbstract

- release-please-config.json
> fix: LSP7 version
