- .gitignore
- .npmignore
- package.json
✅  **Make Solidity contracts from the npm package usable**.
In the 0.2.2 release from npm, only the contract ABIs (as JSON files) can be used.
❌  **The `*.solc` Solidity contracts _(eg: `UniversalProfile.sol`) are_ unusable**. They cannot be imported, because they expect to import contracts from `submodules/ERC725/implementations` and the /submodules folder is not present in the npm package.
The following error occurs when trying to compile a contract that import from the `@lukso/universal-profile-smartcontracts` npm package.
```bash
Error HH404: File ../submodules/ERC725/implementations/contracts/ERC725/ERC725AccountCore.sol, imported from @lukso/universalprofile-smart-contracts/contracts/UniversalProfileCore.sol, not found.
```
- ➕   Add the solidity contracts from the `submodules/` …
> ⚠️   Fix NPM - Add submodules contracts in NPM Package

- .github/workflows/mythx-analysis.yml
MythX CI keeps running on every new commit made to a PR.
It sometimes fail, and make the whole PR look like it is failing, although all the tests + linter checks pass successfully.
I suggest we just add it to be run manually for now, and we change the CI based on what comes out of the discussion in PR #50
> Trigger MythX CI manually only

- .github/workflows/build-and-test.yml
- .github/workflows/create-github-release.yml
- .github/workflows/publish-android-artifacts.yml
- .github/workflows/publish-ios-artifacts.yml
- .github/workflows/publish-npm-artifact.yml
- .github/workflows/solhint.yml
- package-lock.json
- package.json
- **moved solhint inside a `devDependency`** + run as a npm script, instead of installing solhint globally in workflow
= **save 2min 30s** in workflow ⏲️
> Fix solhint CI issue + use Node.js v16 in workflows

- .github/workflows/publish-ios-artifacts.yml
- .mythx.yml
- hardhat.config.ts
- make-ios.js
- make-jar.sh
**NB:** this PR can be merged after #61 has been merged
- removed previous versions of LSP7/8 artifacts (including their extensions), as they cannot be used (cannot mint)
- added `LSP7Mintable` and `LSP8Mintable` in npm, android and ios artifacts
- improve iOS build to use artifacts specified in `hardhat.config.ts`
- added remapping for `@erc725/smart-contracts/` in mythx config file
> Improve iOS artifacts build + add artifacts for Mintable LSP7 / 8

- .gitmodules
Deleted file at root related to submodules that we do not use anymore.
> chore: remove `.gitmodules` file

- contracts/Helpers/KeyManager/KeyManagerHelper.sol
- contracts/LSP6KeyManager/LSP6Constants.sol
- contracts/LSP6KeyManager/LSP6KeyManager.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP6KeyManager/LSP6KeyManagerInit.sol
- contracts/Utils/LSP2Utils.sol
- tests/LSP6KeyManager/LSP6KeyManager.spec.ts
- tests/LSP6KeyManager/LSP6KeyManagerProxy.spec.ts
**new `ADDPERMISSIONS`**
- added check for `ADD` _vs_ `CHANGE` permissions when setting new permissions via `setData` + tests 🧪 
**Refactoring** 
- use `LSP2Utils` to create keys for reading `AddressPermissions:Permissions:<address>`, etc... on ERC725Y key-value store. This is done via the function `generateBytes20MappingWithGroupingKey`  🧰 
- moved all permission keys + values inside `LSP6Constants.sol`
- break-down internal logic of function `_verifypermissions` into smaller internal functions calls: 
- `_verifyCanSetdata`, 
- `_verifyCanExecute`, 
- `_verifyIfAllowedAddress`
- `_verifyIfAllowedFunctions`
**Functions + Variables renamed**
-  ~`_checkPermissions`~ -> now `_verifyPermissions`
- ~`_verifyNonce`~ -> now `_isValidNonce`
- ~`_getUserPermissions`~ -> now …
> feat: `ADDPERMISSIONS` + refactor LSP6Keymanager internal functions names & logic

- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/LSP6KeyManager/LSP6KeyManager.spec.ts
- tests/LSP6KeyManager/LSP6KeyManagerProxy.spec.ts
- tests/utils/helpers.ts
**new feature**
Use solc 0.8.4 custom `error to give more meaningful errors when missing permissions or not authorised addresses / functions.
- `NotAuthorised(permission, from)`
- `NotAllowedAddress(from, to)`
- `NotAllowedFunction(from, to)`
**tests**
Updated unit tests for LSP6KeyManager / LSP6KeyManagerProxy to check custom errors.
**bug fix**
to check if an address has no permission:
- check for 32 x empty 0 bytes when reading ERC725Y storage
- instead of `.length`
> feat: use custom `error` for reverts in KeyManager

- CHANGELOG.md
- hardhat.config.ts
- make-jar.sh
- package-lock.json
- package.json
Adds the `ADDPERMISSION` logic to the KeyManager and custom solidity errors.
Add `LSP7Mintable.sol` and `LSP8Mintable.sol`
Renamed smart contracts from e.g. `LSP7-DigitalAsset.sol` >  `LSP7DigitalAsset.sol`
> release: 0.4.1

- .github/workflows/publish-ios-artifacts.yml
Fix conflict with new branch of same name with updated artifacts, when pushing new branch to origin.
-> Update iOS release CI to delete branch `abi-update-release` at the origin (`universal-profiles-ios-sdk`) before push.
> ci: fix failing iOS CI for 0.4.1 release

- tests/utils/constants.ts
Removed this key from the constant file in the tests, so that we don't use it by mistake.
> test: remove deprecated key `SupportedStandards:LSP4DigitalCertificate`

- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/LSP6KeyManager/LSP6KeyManager.spec.ts
- tests/LSP6KeyManager/LSP6KeyManagerProxy.spec.ts
Save gas on deployment by shortening the revert messgae in the require statement.
Removing **KeyManager:** on each message won't affect the context.
⬇️ Saves 30,435 gas ⬇️ | deployed on L14 
- Link to the normal KeyManager on Blockscout:  https://blockscout.com/lukso/l14/tx/0xe65c411f925f3b2e2aa613abbc99624c777c5581d95ccb09db23f278517e472c/internal-transactions
- Link to the Optimzed KeyManager on Blockscout:  https://blockscout.com/lukso/l14/tx/0x189b1d378db858fbe067864256c0d3724aea21176f934f96f25e8e9d10e46b5e/internal-transactions
> perf: sav gas in the KeyManager

- contracts/LSP6KeyManager/LSP6Constants.sol
- tests/LSP9Vault/LSP9Vault.spec.ts
- tests/UniversalProfile.spec.ts
This PR was introduced based on a discussion from #82 
**Contracts**
- use hardcoded constants for ERC165 interface identifiers.
**Tests**
- replace occurences of interfaceIDs literals in test files with reference to `constants.ts` file.
> refactor: use constants for interfaceIds in Solidity

- .github/workflows/build-artifacts.yml
- .github/workflows/create-github-release.yml
- .github/workflows/publish-android-artifacts.yml
Android build steps were temporary removed as Web3J installation was broken. Web3J installation is now fixed so can add android steps back. See https://github.com/web3j/web3j/issues/1579
> ci: readd android build and release steps

- constants.ts
- package-lock.json
- package.json
- tests/UniversalProfile.spec.ts
- tests/UniversalProfileProxy.spec.ts
The 2 entries `elementValueType` and `elementValueContent` are not specified anymore in LSP2 Schema. So remove them.
Also edited two test descriptions for more precision.
> refactor: remove deprecated LSP2 `elementValueContent` and `elementValueType`

- contracts/Helpers/SignatureValidatorContract.sol
- contracts/Helpers/TargetContract.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/Utils/LSP6Utils.sol
- tests/LSP6KeyManager/LSP6KeyManager.spec.ts
added feature + test for `ALLOWEDSTANDARDS`
- added check for `isContract` for `to` address
> feature: add check for `ALLOWEDSTANDARDS` in KeyManager

- tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP.spec.ts
- tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault.spec.ts
- tests/LSP7DigitalAsset/LSP7DigitalAsset.behaviour.ts
- tests/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.behaviour.ts
- tests/UniversalProfile.spec.ts
- tests/UniversalProfileProxy.spec.ts
added tests to verify contracts support `ERC165` interface + the following interface:
- `ERC725Y` in LSP7 / 8
- `ILSP1Delegate` in URD (for Universal Profile and Vault)
- `ERC725Account` (LSP0) in Universal Profile
> test: add missing tests for `supportInterface`

- contracts/Helpers/SignatureValidatorContract.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibilityForERC721.sol
- tests/LSP6KeyManager/LSP6KeyManager.spec.ts
- Dismissed all the linter warnings with solhint comments, so that they don't display anymore on future PRs
These warnings were related to unused function variables in `LSP8CompatibilityForERC721` + `SignatureValidator` (helper) contracts
> chore: linter warnings

- .github/workflows/publish-ios-artifacts.yml
Removes conditional from ios artifact publish. This is already handled by the `build-artifacts` workflow so is not needed here
> ci: remove conditional ios artifact publish

- contracts/Helpers/Tokens/LSP4CompatibilityTester.sol
- contracts/Helpers/Tokens/LSP7CompatibilityForERC20InitTester.sol
- contracts/Helpers/Tokens/LSP7CompatibilityForERC20Tester.sol
- contracts/LSP4DigitalAssetMetadata/LSP4Compatibility.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAsset.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetInitAbstract.sol
- contracts/LSP7DigitalAsset/extensions/ILSP7CompatibilityForERC20.sol
- contracts/LSP7DigitalAsset/extensions/LSP7CompatibilityForERC20Core.sol
- contracts/LSP7DigitalAsset/extensions/LSP7CompatibilityForERC20Init.sol
- contracts/LSP7DigitalAsset/extensions/LSP7CompatibilityForERC20InitAbstract.sol
- docs/ILSP7CompatibilityForERC20.md
- docs/LSP7CompatibilityForERC20.md
- docs/LSP7CompatibilityForERC20Core.md
- docs/LSP7CompatibilityForERC20Init.md
- docs/LSP7CompatibilityForERC20InitAbstract.md
- docs/LSP7CompatibilityForERC20InitTester.md
- docs/LSP7CompatibilityForERC20Tester.md
- docs/SignatureValidator.md
- tests/LSP7DigitalAsset/extensions/LSP7CompatibilityForERC20.behaviour.ts
- tests/LSP7DigitalAsset/extensions/LSP7CompatibilityForERC20.spec.ts
Adds a contract LSP7CompatabilityForERC20Init for the proxy version. This was left out after the change from an abstract contract to a constructor version, and is being implemented this way to support the pattern to have a constructor and proxy version.
> Lsp7compat proxy and erc20 events

- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/Handling/TokenAndVaultHandling.sol
- Add a security check to confirm that the profile(msg.sender) is the same profile linked to the extracted Key Manager.
> fix: security check in UniversalReceiverDelegateUP contract

- CHANGELOG.md
- package-lock.json
- package.json
- Bump minor version in `package.json`: 0.4.3 > **0.5.0**
- Prepare `CHANGELOG.md`
> chore(release): 0.5.0

- .github/workflows/publish-ios-artifacts.yml
Improve iOS artefacts release. Checks out main before publishing swift SDK
> ci: checkout main before pushing iOS artifacts

- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP6KeyManager/LSP6Utils.sol
- tests/LSP6KeyManager/LSP6KeyManager.spec.ts
- tests/LSP6KeyManager/LSP6KeyManagerProxy.spec.ts
- tests/utils/helpers.ts
When calling the function `isValidSignature(...)` with a message signed by an `address` that has no permissions set on the `account` linked to the Key Manager, the output / returned value should be the **ERC1271 FAIL VALUE** (`0xffffffff`).
The function `isValidSignature(...)` on the Key Manager reverts with the error message `no permission set for this user` when the signed message comes from an address that has no permission set.
- **new feature:**  use custom Solidity `error` called `NoPermissionsSet`
> fix: `isValidSignature(...)` on LSP6 revert on empty permissions

- contracts/LSP0ERC725Account/LSP0ERC725Account.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountInit.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountInitAbstract.sol
- contracts/LSP4DigitalAssetMetadata/LSP4Compatibility.sol
- contracts/LSP6KeyManager/LSP6KeyManagerInitAbstract.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAsset.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetInit.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetInitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetInit.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetInitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibilityForERC721.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibilityForERC721Core.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibilityForERC721InitAbstract.sol
- contracts/LSP9Vault/LSP9Vault.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- contracts/LSP9Vault/LSP9VaultInit.sol
- contracts/LSP9Vault/LSP9VaultInitAbstract.sol
These steps made an LSP7 token transfer cheaper by **10,658 gas units.**
> fix: security + gas optimization

- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/Handling/TokenAndVaultHandling.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/Handling/TokenHandling.sol
- Calling the `universalReceiver` function in LSP0, LSP9 with a specific `typeId` related to token hooks will allow making the caller address registered as an asset or vault in the LSP5/LSP10 array keys.
This will prevent spamming the storage of vaults and UPs by EOAs. 
Will add 288 gas unit.
> fix: add sender code length check in UniversalReceiverDelegate

- constants.ts
- contracts/Helpers/KeyManager/KeyManagerHelper.sol
- contracts/LSP6KeyManager/ILSP6KeyManager.sol
- contracts/LSP6KeyManager/LSP6Constants.sol
- contracts/LSP6KeyManager/LSP6KeyManager.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP6KeyManager/LSP6KeyManagerInitAbstract.sol
This PR introduces a breaking in the LSP6 interface. changing LSP6 interface ID.
- **LSP6 interface ID (before):** `0x6f4df48b `
- **LSP6 interface ID (after):**  `0x32e6d0ab `
## Features
> feat(lsp6)!: add `account()` function as part of the LSP6 interface

- contracts/Helpers/ERC165CheckerCustomTest.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/Handling/TokenAndVaultHandling.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/Handling/TokenHandling.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- contracts/Utils/ERC165CheckerCustom.sol
- tests/Helpers/ERC165CheckerCustom.test.ts
After discussing with @CJ42 about the gas cost of `ERC165Checker` which is approximately **~10k gas unit**, we decided to create a custom implementation of `ERC165Checker` that only checks for the InterfaceID we want to query and drop checking the ERC165 and `0xffffffff` InterfaceIDs. 
It will save **~3,1k gas unit** on each call, resulting in a **~31k gas unit** saving on a normal token transfer scenario.
> feat: use custom version of `ERC165Checker`

- hardhat.config.ts
Add artifacts for `LSP4DigitalAssetMetadata` in the npm package, so that contracts and interfaces can use this ABI to just fetch token or NFT (LSP7 / LSP8) metadata.
> build(lsp4): add LSP4 artifacts in package

- .github/workflows/publish-ios-artifacts.yml
Command `git describe --tags --abbrev=0` will print version as `v0.5.0`. 
It is saved into the variable and that variable is used in the commit message.
Try this out in console:
```
test_var=$(git describe --tags --abbrev=0)
echo "Test var content: $test_var"
```
> ci: add smart contract version number to commit msg in iOS workflow

- contracts/Helpers/KeyManager/KeyManagerInternalsTester.sol
- tests/LSP6KeyManager/LSP6KeyManager.test.ts
- tests/LSP6KeyManager/internals/AllowedAddresses.internal.ts
- tests/LSP6KeyManager/internals/AllowedFunctions.internal.ts
- tests/LSP6KeyManager/internals/ReadPermissions.internal.ts
- tests/LSP6KeyManager/tests/PermissionChangeAddPermissions.test.ts
- tests/LSP6KeyManager/tests/PermissionSetData.test.ts
- tests/LSP6KeyManager/tests/PermissionTransferValue.test.ts
- tests/utils/context.ts
- tests/utils/fixtures.ts
- tests/utils/helpers.ts
> tests: add tests for UP to UP interaction + use explicit names for contracts that test internal functions

- .prettierrc
- Decreasing the `printWidth` in prettier from 120 to 100 (recommended by solidity docs).
> chore: decrease prettier `printWidth` to 100

- contracts/LSP6KeyManager/ILSP6KeyManager.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
Similar to https://github.com/ERC725Alliance/ERC725/pull/98
Save gas by only use the first 4 bytes of the `_data` payload (= function selector) in the `Executed` event in LSP6.
> refactor(lsp6): use bytes4 selector in `Executed` event

- contracts/Helpers/KeyManager/KeyManagerHelper.sol
- contracts/LSP6KeyManager/LSP6Errors.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP6KeyManager/LSP6Utils.sol
- tests/LSP6KeyManager/LSP6KeyManager.behaviour.ts
- tests/LSP6KeyManager/LSP6KeyManager.test.ts
- tests/LSP6KeyManager/internals/AllowedAddresses.internal.ts
- tests/LSP6KeyManager/internals/AllowedERC725YKeys.internal.ts
- tests/LSP6KeyManager/internals/index.ts
- tests/LSP6KeyManager/tests/AllowedAddresses.test.ts
- tests/LSP6KeyManager/tests/AllowedERC725YKeys.test.ts
- tests/LSP6KeyManager/tests/AllowedFunctions.test.ts
- tests/LSP6KeyManager/tests/PermissionCall.test.ts
- tests/LSP6KeyManager/tests/PermissionChangeAddPermissions.test.ts
- tests/LSP6KeyManager/tests/PermissionDeploy.test.ts
- tests/LSP6KeyManager/tests/PermissionSetData.test.ts
- tests/LSP6KeyManager/tests/PermissionStaticCall.test.ts
- tests/LSP6KeyManager/tests/PermissionTransferValue.test.ts
- tests/LSP6KeyManager/tests/Security.test.ts
- tests/LSP9Vault/LSP9Vault.behaviour.ts
🐛  🩹  **Bug Fixes**
The `try { ... } catch { ... }` blocks in the test suite are misleading and do not run the assertion if the contract call goes successfully (while it is expected to revert).
After re-writing the test, it appears that the `AllowedERC725YKeys` feature does not work properly depending on the keys given as inputs.
> fix(lsp6): fix bugs for `AllowedERC725YKeys` when input is multiple keys that include allowed + not allowed keys

- constants.ts
- contracts/Helpers/KeyManager/KeyManagerInternalsTester.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/Handling/TokenAndVaultHandling.sol
- contracts/LSP6KeyManager/ILSP6KeyManager.sol
- contracts/LSP6KeyManager/LSP6Constants.sol
- contracts/LSP6KeyManager/LSP6KeyManager.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP6KeyManager/LSP6KeyManagerInitAbstract.sol
- tests/LSP6KeyManager/LSP6KeyManager.behaviour.ts
Edit the LSP6 interface function from `account()` -> `target()`
This make the LSP6 interface ID change from:
- **before:** `0x32e6d0ab `
- **after:** `0xbbf5cd19 `
> refactor!: change function `account()` -> `target()` in LSP6

- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- Changed all occurrences of `> 0` to `!= 0` because `!= 0` is cheaper than `> 0`.
These two statements are equivalent for uint values since they cannot be less than zero.
> refactor: use `!= 0` instead of `> 0`

- README.md
- hardhat.config.ts
LSP0 was already in the list of artifacts, but as duplicate in the standard and proxy section of the artifacts list
- add proxy version of LSP0 (= `LSP0ERC725AccountInit`) in artifacts list.
- _docs.lukso.tech_ ([Standard](https://docs.lukso.tech/standards/introduction) + [contract API](https://docs.lukso.tech/standards/smart-contracts/introduction) docs)
- [LSP](https://github.com/lukso-network/LIPs) repository.
> docs: change `UniversalProfile` -> `LSP0ERC725Account` in README + fix broken links

- constants.ts
- contracts/LSP6KeyManager/ILSP6KeyManager.sol
- contracts/LSP6KeyManager/LSP6Constants.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/LSP6KeyManager/tests/AllowedFunctions.test.ts
- tests/LSP6KeyManager/tests/MultiChannelNonce.test.ts
- tests/LSP6KeyManager/tests/PermissionCall.test.ts
- tests/LSP6KeyManager/tests/Security.test.ts
- Include chainId in the signed message in `executeRelayCall(..)` as mentioned in issue [#151](https://github.com/lukso-network/lsp-smart-contracts/issues/151).
- Change all occurrences of `_data` to `_calldata` in LSP6.
- Remove unnecessary param in `executeRelayCall(...)`: `_signedFor` param as it will be included in the signed message.
- Re-order params in `executeRelayCall(..)` (dynamic param is the last one) to be able to extract the `_calldata`. 
- Change the interfaceId of LSP6 from `0xbbf5cd19` to `0xc403d48f` since function signature of `executeRelayCall(..)` changed.
> fix: include `chainId` in signed message in `executeRelayCall(..)`

- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- Sending `msg.value` to the account instead of 0.
This will prevent value to be stuck in the KM.
> fix: send the `msg.value` instead of 0 in `executeRelayCall(..)`

- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- Introducing `ErrorHandlerLib` in `execute(...)` and `executeRelayCall(..)` to support custom errors.
> feat: add ErrorHandlerLib in LSP6

- constants.ts
- contracts/Helpers/ERC165Interfaces.sol
- contracts/LSP0ERC725Account/LSP0ERC725Account.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountInitAbstract.sol
- contracts/LSP9Vault/LSP9Constants.sol
- contracts/LSP9Vault/LSP9Vault.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- contracts/LSP9Vault/LSP9VaultInitAbstract.sol
- contracts/Utils/ClaimOwnership.sol
- tests/ClaimOwnership.behaviour.ts
- tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP.behaviour.ts
- tests/LSP9Vault/LSP9Vault.behaviour.ts
- tests/LSP9Vault/LSP9Vault.test.ts
- tests/UniversalProfile.test.ts
- move hooks `_notifyVaultSender(address)` and `_notifyVaultReceiver(addresss)` from `transferOwnership(address)` -> `claimOwnership()` function = **only notify + run these hooks when ownership has been fully transferred and claimed.**
- add claimOwnership test for Proxy version of Universal Profile
> feat!: add ClaimOwnership in LSP9 Vault

- DEPLOYMENT.md
- hardhat.config.ts
- package-lock.json
- package.json
[An issue (#2661) was raised on Hardhat repository](https://github.com/NomicFoundation/hardhat/pull/2661) to add LUKSO L14 chain.
The objective was to add the L14 chain configs in `@nomiclabs/hardhat-etherscan`to be able to verify easily contracts deployed on L14. See docs of the plugin for more infos: https://github.com/NomicFoundation/hardhat/tree/master/packages/hardhat-etherscan
[This issue was solved in the following PR in hardhat](https://github.com/NomicFoundation/hardhat/pull/2597), and it is now possible to add custom chain to chain in the `@nomiclabs/hardhat-etherscan` plugin via the `hardhat.config.ts` file
- add release candidate version of `@nomiclabs/hardhat-etherscan@rc` in dev dependencies, so to enable verifying deployed contracts via CLI.
- add L14 chain configs in the …
> chore: add hardhat-etherscan dependency to verify contracts on L14

- constants.ts
- contracts/Helpers/ERC165Interfaces.sol
- contracts/LSP0ERC725Account/LSP0Constants.sol
- contracts/LSP9Vault/LSP9Constants.sol
Based on the changes in the specifications of LSP0 + LSLP9:
> refactor!: edit LSP0 + LSP9 interface IDs to include `owner()` + `transferOwnership()`

- contracts/LSP0ERC725Account/LSP0ERC725Account.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountInitAbstract.sol
- contracts/LSP9Vault/LSP9Vault.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- contracts/LSP9Vault/LSP9VaultInitAbstract.sol
- Simplifying inheritance of LSP0 and LSP9 by removing the inheritance of ERC725 and setting the owner manually in the constructor/initializer.
- Style functions in ERC order with adding few nastpec comments.
> refactor: simplify inheritance in LSP0 & LSP9

- contracts/LSP5ReceivedAssets/LSP5Utils.sol
- tests/utils/fixtures.ts
- Changing the arranging of the data set for `LSP5-ReceivedAssetsMap` and `LSP10-VaultsMap` according to the specs. 
[LSP5-ReceivedAssetsMap](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-5-ReceivedAssets.md#lsp5receivedassetsmap)
[LSP10-VaultsMap](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-10-ReceivedVaults.md#lsp10vaultsmap)
> refactor: flip `index` and `interfaceId` in LSP5 & LSP10

- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/LSP6KeyManager/tests/PermissionDelegateCall.test.ts
⚠️ As discussed and agreed, we want to disallow DELEGATECALL for any ERC725 account linked to this KeyManager for safety reasons, as **delegatecall is a dangerous operation** that can introduce side effects on the linked account's storage.
- use `OPERATION_TYPE` constants imported from `@erc725/smart-contracts` package.
> refactor!: disable operation type DELEGATECALL in KeyManager

- contracts/Helpers/ERC165Interfaces.sol
- contracts/LSP0ERC725Account/LSP0ERC725Account.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountInitAbstract.sol
- contracts/LSP4DigitalAssetMetadata/LSP4DigitalAssetMetadataInitAbstract.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAsset.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetInitAbstract.sol
- contracts/LSP7DigitalAsset/extensions/LSP7CappedSupplyInitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetInitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CappedSupplyInitAbstract.sol
- contracts/LSP9Vault/LSP9Vault.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- contracts/LSP9Vault/LSP9VaultInitAbstract.sol
- contracts/Utils/ClaimOwnership.sol
- package-lock.json
- package.json
- Upgrading  `@erc725/smart-contracts` package with the necessary changes:
- Changing `OwnableUnset` path to custom folder 
- Use `_setOwner` function instead of `initOwner`
- Introduce custom `Initializable` contract in LSP0 & LSP9
- Remove unnecessary import statements.
> build: upgrade `@erc725/smart-contracts` package

- constants.js
- contracts/LSP10ReceivedVaults/LSP10Constants.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/Handling/TokenAndVaultHandling.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/Handling/TokenHandling.sol
- contracts/LSP2ERC725YJSONSchema/LSP2Utils.sol
- contracts/LSP4DigitalAssetMetadata/LSP4Constants.sol
- contracts/LSP5ReceivedAssets/LSP5Constants.sol
- contracts/LSP5ReceivedAssets/LSP5Utils.sol
- contracts/LSP6KeyManager/LSP6Constants.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP6KeyManager/LSP6Utils.sol
- contracts/LSP9Vault/LSP9Constants.sol
- contracts/UniversalProfile.sol
- contracts/UniversalProfileInitAbstract.sol
- tests/LSP6KeyManager/tests/PermissionSetData.test.ts
- tests/UniversalProfile.behaviour.ts
- Edit all keys and functions to match the new spec of the [LSP2-ERC725YJSONSchema Standard](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-2-ERC725YJSONSchema.md) after the change in this [commit](https://github.com/lukso-network/LIPs/commit/2d2c727956ad1fe0bcbb496e6719a626925b116b).
- Smart Contract Including:
- `KeyManagerCore.sol` to handle the permission key after changing from `bytes8` to `bytes6`
- Key Changes Including:
- Change in `.sol` const files
- Change in `.js` const files
- Change in `LSP2Utils` library
- Test Changes Include:
- UniversalProfile Tests (Related to LSP12IssuedAssets)
- LSP6KeyManager Tests (Related to LSP12IssuedAssets)
- Change Naming of function to match KeyType in `LSP5Utils` lib
> refactor!: edit LSP2 keys according to new spec

- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
`LSP0ERC725AccountCore` and `LSP9VaultCore` contracts uses `BytesLib` library to convert the raw bytes of `LSP1UniversalReceiverDelegate` data key (fetched from the ERC725Y key-value store) in the `universalReceiver(...)` function.
Remove the `BytesLib` library in this function and use explicit type casting.with `address(bytes20(...))`.
This:
- reduces the LSP0 and LSP9 contract bytecode by 114 bytes (= slightly cheaper deployment cost)
- save 84 gas when calling the `universalReceiver(...)` function.
> refactor: use type casting instead of `BytesLib` library for `universalReceiver()` function

- package-lock.json
- package.json
- tests/LSP7DigitalAsset/LSP7DigitalAsset.behaviour.ts
- tests/LSP7DigitalAsset/extensions/LSP7CompatibilityForERC20.behaviour.ts
- tests/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.behaviour.ts
- tests/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibilityForERC721.behaviour.ts
- tests/LSP9Vault/LSP9Vault.behaviour.ts
> fix: remove `dataValue` param from DataChanged event

- contracts/Helpers/Executor.sol
- contracts/LSP6KeyManager/LSP6Constants.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/LSP6KeyManager/tests/AllowedERC725YKeys.test.ts
- tests/LSP6KeyManager/tests/AllowedStandards.test.ts
- tests/LSP6KeyManager/tests/PermissionChangeAddPermissions.test.ts
- tests/LSP6KeyManager/tests/PermissionChangeOwner.test.ts
- tests/LSP6KeyManager/tests/PermissionSetData.test.ts
https://github.com/ERC725Alliance/ERC725/pull/93 introduced a function overloading that allows setting a single data key.
The current implementation of the KeyManager does not recognise the `setData(bytes32,bytes)` selector. But only `setData(bytes32[],bytes[])` for an array of data keys.
This is problematic for protocols and interfaces, as it requires them to create arrays containing a single element for setting a single element.
This is more problematic, especially for protocols and smart contracts looking to set only one single data key, as it increases the gas cost by requiring to create of a memory array with one single entry.
> feat: add path for `setData(bytes32,bytes)` in `LSP6KeyManager`

- contracts/LSP4DigitalAssetMetadata/LSP4DigitalAssetMetadata.sol
- contracts/LSP4DigitalAssetMetadata/LSP4DigitalAssetMetadataInitAbstract.sol
remove reference to parent contract in overloaded `_setData(...)` function in LSP4 (function overloaded to check that not overriding data keys `TOKEN_NAME` and `TOKEN_SYMBOL`
> perf: save 2,140 gas on deployment of LSP4

- .github/workflows/build-artifacts.yml
- .github/workflows/build-lint-test.yml
- .github/workflows/mythx-analysis.yml
- .github/workflows/publish-npm-artifact.yml
Recently, the CI on the repository failed at the step of installing the dependencies with `npm ci`. After investigation, this seems to be due to different versions of Node.js being used in different workflows.
(click on step named "Use Node.js '16.x' to see details)
- Node.js version node v16.15.0 (npm v8.5.5) -> OK ✅  (_e.g._ https://github.com/lukso-network/lsp-smart-contracts/runs/6780284640?check_suite_focus=true)
- Node.js version v16.15.1 (npm v8.11.0) -> fail ❌ (e.g. https://github.com/lukso-network/lsp-smart-contracts/runs/6824463119?check_suite_focus=true)
Maybe this is due to the fact that version 16.15.1 upgraded to npm 8.11?
Installing the dependencies with version 16.15.0 succeed ✅ 
```bash
nvm install 16.15.0
nvm use 16.15.0
npm ci
```
output
```bash
added 2978 packages, and …
```
> ci: use Node.js version 16.15.0

- README.md
- constants.js
[Solidity 0.8.4](https://github.com/ethereum/solidity/releases/tag/v0.8.4) introduce custom `error`. These custom revert errors can be accessed from the EVM memory and identified like functions, using a `bytes4` selector (= first 4 bytes of the keccak256 hash of the error signature).
> See this Solidity blog post for more info: https://blog.soliditylang.org/2021/04/21/custom-errors/
add the list of Errors selectors in `constants.js`, including their name and message description of the error, so that these can be used by client interfaces to process + display error messages in a human readable format.
> build: add error signatures in `constants.js`

- constants.js
- contracts/Helpers/Tokens/TokenReceiverWithLSP1.sol
- contracts/Helpers/UniversalReceivers/UniversalReceiverDelegateRevert.sol
- contracts/Helpers/UniversalReceivers/UniversalReceiverTester.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP1UniversalReceiver/ILSP1UniversalReceiver.sol
- contracts/LSP1UniversalReceiver/ILSP1UniversalReceiverDelegate.sol
- contracts/LSP1UniversalReceiver/LSP1Constants.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/LSP1UniversalReceiverDelegateVault.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- contracts/Legacy/UniversalReceiverAddressStore.sol
- tests/LSP1UniversalReceiver/LSP1UniversalReceiver.behaviour.ts
- Mark `universalReceiver(..)` function as payable
- Add `value` param to `universalReceiverDelegate(..)` function
- Add `value` param to UniversalReceiver event
- Update LSP1Delegate InterfaceID
> feat: update universalReceiver to latest spec

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): prepare rc-0.6.1

- contracts/Helpers/KeyManager/KeyManagerInternalsTester.sol
- contracts/LSP2ERC725YJSONSchema/LSP2Utils.sol
- contracts/LSP6KeyManager/ILSP6KeyManager.sol
- contracts/LSP6KeyManager/LSP6Errors.sol
- contracts/LSP6KeyManager/LSP6KeyManager.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP6KeyManager/LSP6KeyManagerInit.sol
- contracts/LSP6KeyManager/LSP6KeyManagerInitAbstract.sol
- contracts/LSP6KeyManager/LSP6Utils.sol
- contracts/Utils/UtilsLib.sol
- tests/LSP6KeyManager/internals/AllowedERC725YKeys.internal.ts
After analyzing the LSP6 contracts with slither (static analysis tool)
> fix: use safer code for LSP6 - Key Manager contracts and improve styles

- DEPLOYMENT.md
Improve the Deployment doc, the current documentation guide on deployment doesn't specify how to get fauset and deploy successfully:
> docs: Add documentation for feature DEPLOYMENT.md

- contracts/Factories/UniversalFactory.sol
- contracts/LSP0ERC725Account/LSP0ERC725Account.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountInit.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountInitAbstract.sol
- contracts/UniversalProfile.sol
- contracts/UniversalProfileInit.sol
- contracts/UniversalProfileInitAbstract.sol
- tests/Factories/UniversalFactory.test.ts
- tests/UniversalProfile.test.ts
- tests/utils/helpers.ts
When using the proxy versions of `LSP0ERC725AccountInit` and `UniversalProfileInit`, these contracts are uninitialized on deployment.
⚠️  This creates a race condition for base (= implementation) contracts on deployment, as it requires to call the `_initialize(...)` function on the base contracts **after deployment**. This lead to the possibility of an external actor calling the `initialize(...)` function straight after deployment, then making it the owner and having control over the base implementation.
> fix!: lock LSP0 and LSP3 base contracts on deployment

- contracts/Helpers/Tokens/LSP7CompatibilityForERC20InitTester.sol
- contracts/LSP7DigitalAsset/extensions/ILSP7CompatibilityForERC20.sol
- contracts/LSP7DigitalAsset/extensions/LSP7CompatibilityForERC20Core.sol
- contracts/LSP7DigitalAsset/extensions/LSP7CompatibilityForERC20Init.sol
- tests/LSP7DigitalAsset/extensions/LSP7CompatibilityForERC20.test.ts
In the `LSP7CompatibilityForERC20` implementation, the following functions do not behave completely in the same way as the functions defined in a standard `ERC20` interface:
[**standard** `ERC20` implementation from OpenZeppelin.](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/IERC20.sol)
```solidity
function approve(address spender, uint256 amount) external returns (bool);
function transfer(address to, uint256 amount) external returns (bool);
function transferFrom(
address from,
address to,
uint256 amount
) external returns (bool);
```
Functions defined in `LSP7CompatibilityForERC20Core`
```solidity
function approve(address operator, uint256 amount) external virtual override {
// ...
}
function transfer(address to, uint256 amount) external …
```
> fix!: backward compatibility for `LSP7CompatibilityForERC20` for return statements + lock base contract on deployment

- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- Adding virtual keyword to the fallback function in LSP0/LSP9
> chore: add `virtual` keyword to the fallback function

- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP9Vault/LSP9Vault.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- contracts/LSP9Vault/LSP9VaultInit.sol
- contracts/LSP9Vault/LSP9VaultInitAbstract.sol
- tests/LSP9Vault/LSP9Vault.test.ts
> fix!: lock LSP9 base contracts on deployment + improve variable names

- contracts/Custom/ClaimOwnership.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP6KeyManager/LSP6KeyManagerInit.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP7DigitalAsset/extensions/LSP7CompatibilityForERC20Core.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibilityForERC721Core.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- Allowing for more flexibility with inheriting the lsp-smart-contracts, visibility changed from `external` to `public` in some functions.
> refactor: change `external` visibility to `public`

- contracts/LSP7DigitalAsset/extensions/LSP7CappedSupplyInitAbstract.sol
- contracts/LSP7DigitalAsset/presets/LSP7MintableInit.sol
- contracts/LSP7DigitalAsset/presets/LSP7MintableInitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CappedSupplyInitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8MintableInit.sol
- deploy/011_deploy_base_lsp8_mintable.ts
> fix: assets inheritance + lock `LSP8MintableInit` base contract on deployment

- contracts/LSP0ERC725Account/LSP0ERC725AccountInit.sol
- contracts/LSP6KeyManager/LSP6KeyManagerInit.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetInit.sol
- contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20Init.sol
- contracts/LSP7DigitalAsset/presets/LSP7MintableInit.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetInit.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8MintableInit.sol
- contracts/LSP9Vault/LSP9VaultInit.sol
- contracts/UniversalProfileInit.sol
Use the `_disableInitializers()` method inside of the base contract (= `Init` versions), so to prevent reinitializing any of the base contract via inheritance.
> refactor: :recycle: prevent reinitializing via inheritance on base contracts

- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/LSP6KeyManager/tests/PermissionChangeAddPermissions.test.ts
as reported by @dzbo , it is not possible to clear the array of allowed addresses, functions, standards or ERC725Y data keys (= reset from a list/abi-encoded array back to `0x`).
> fix: enable to clear array for allowed data key permissions

- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/LSP6KeyManager/tests/AllowedERC725YKeys.test.ts
The `AllowedERC725YKey` feature in the LSP6 Key Manager currently does not allowed to set `0x0000000000000000000000000000000000000000000000000000000000000000` (= `bytes32(0)` or 32 x `00` bytes) as an allowed ERC725YKey.
If a controller address has this data key in its list of allowed ERC725Y data key, the check against the allowed data key leads to **integer underflow when counting the number of zero trailing bytes** 🚫 in the allowed data key _(see screenshot below)._
As a result, this can lead the controller to be stuck and prevent the controller address from setting data on the account linked to this KeyManager.
This PR fixes this bug, while also allowing to whitelist any allowed ERC725Y data key by setting the **zero-key** `0x00000000...00000000` in the list of allowed ERC725Y data …
> fix: underflow error for AllowedERC725YKey + allow to set the zero key `0x00000000...00000000` via the Key Manager

- CHANGELOG.md
- package-lock.json
- package.json
> this PR is awaiting a new release of `@erc725/smart-contracts`. See https://github.com/ERC725Alliance/ERC725/pull/144
Preparing release 0.6.2
> chore: prepare release 0.6.2

- contracts/LSP7DigitalAsset/ILSP7DigitalAsset.sol
- contracts/LSP8IdentifiableDigitalAsset/ILSP8IdentifiableDigitalAsset.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
Fixed an issue in Natspec docs of LSP7/LSP8 + improved `@title` tag
> docs: edit comments title for LSP7/LSP8 interface

- contracts/Custom/ERC165Checker.sol
- package-lock.json
- package.json
> chore: update of OpenZeppelin package and the custom ERC165Checker

- contracts/Helpers/Executor.sol
- contracts/LSP6KeyManager/LSP6Constants.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP6KeyManager/LSP6Utils.sol
Version `3.1.1` of `@erc725/smart-contracts` introduce the `bytes4` function selectors of the overloaded functions `setData(bytes32,bytes)` or `setData(bytes32[],bytes[])`.
https://github.com/ERC725Alliance/ERC725/releases/tag/v3.1.1
Use the selectors from this npm package to improve readability.
> refactor: use ERC725Y overloaded selectors from @erc725 npm package

- contracts/LSP0ERC725Account/LSP0ERC725AccountInitAbstract.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20Core.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- contracts/LSP9Vault/LSP9VaultInitAbstract.sol
- package-lock.json
- package.json
- tests/LSP7DigitalAsset/LSP7DigitalAsset.test.ts
- tests/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.test.ts
- tests/LSP7DigitalAsset/extensions/LSP7Mintable.test.ts
- tests/LSP9Vault/LSP9Vault.test.ts
- tests/UniversalProfile.test.ts
Closes #233
Will need also to release erc725 smart contract after this change: https://github.com/ERC725Alliance/ERC725/pull/150
> refactor: use OZ-upgradeable contracts to avoid conflicts in Init contracts

- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/ILSP8CompatibleERC721.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721Core.sol
- tests/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.behaviour.ts
- tests/utils/helpers.ts
The backward compatible version of LSP8 with ERC721 is missing a function `setApprovalForAll(...)` that is part of the ERC721 interface.
This PR introduces this function in `LSP8CompatibleERC721` alongside a mapping `_operatorsApprovals` storing the operators address that are approved for all tokenIds owned by a `tokenOwner`.
> **NB:** gas cost of `transferFrom(...)` with `LSP8CompatibleERC721` is around 188k gas.
> fix: add `setApprovalForAll(...)` in `LSP8CompatibleERC721`

- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721Core.sol
- https://github.com/lukso-network/lsp-smart-contracts/pull/238 removed the Context contract but another following PR, made a fix on a contract that included some functions of Context Contract.
This PR will remove the functions related to Context contract so the contracts can compile successfully.
> chore: remove functions of Context contract

- tests/ClaimOwnership.behaviour.ts
- tests/LSP1UniversalReceiver/LSP1UniversalReceiver.behaviour.ts
- tests/UniversalProfile.behaviour.ts
- tests/UniversalProfile.test.ts
Hardhat comes with very convenient Chai matchers for testing events. These can be used to test more easily events and their parameters (instead of using the old method of going through the logs and searching each topics).
This PR refactor the tests that check for proper event emissions for the following events:
- `ValueReceived`
- `UniversalReceiver`
- `OwnershipTransferred`
> test: simplify testing events using Hardhat Chai matchers

- contracts/Factories/UniversalFactory.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
`!=0` is a cheaper operation than `>0` and safe to use on `uint` with solidity `ˆ0.8.0` 
#242
> refactor: replace >0 by !=0

- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/LSP6KeyManager/tests/AllowedERC725YKeys.test.ts
The former tests for **AllowedERC725YKeys** were not checking the right and expected behaviour when one of the allowed ERC725Y key in the list for the caller is `bytes32(0)`.
In `LSP6KeyManagerCore`, the function `_countTrailingZeroBytes(...)` does not check the byte at the index properly.
Refactored this function to ensure the function works properly when `key == `bytes32(0)`, while optimising for gas usage.
Add additional test with an allowed data key that contains one single byte (e.g: `0xaa00000000...00000000`), to check that looking for a specific `nByte` at a byte index inside the allowed data key works properly.
> fix: [QSP-6] fix incorrect index check for `_countTrailingZeroBytes(...)` in `LSP6KeyManagerCore.sol`

- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/Handling/TokenAndVaultHandling.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/Handling/TokenHandling.sol
- tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP.behaviour.ts
- Remove code length check in UniversalReceiverDelegate. 
This line of code was initially added to prevent EOAs from calling the `universalReceiver(..)` function with a receiving `typeId` (LSP7 || LSP8 || LSP9) and registering their addresses as assets in the storage.
The very interesting edge case for this code is:
When a call is made by a constructor of a contract, the code length will still be 0 since it's not returned yet. We do not want to block external calls from the constructor as we need this behavior to register the addresses of vaults inside the UP storage on deployment. Also, I think in the future, there will be some tokens minting inside the constructor, we want these tokens to also be registered inside the UP storage. That's why we should remove the code length check. …
> fix: remove code length check in UniversalReceiverDelegate

- contracts/LSP8IdentifiableDigitalAsset/ILSP8IdentifiableDigitalAsset.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8Errors.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- tests/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.behaviour.ts
In LSP8, an operator can only be revoked by the token owner via the `revokeOperator(...)` function.
However, any operator can revoke another operator, and all the operators related to the `tokenId` by calling the function `transfer(...)` function with the same address for `from` and `to` (`from == to`).
If the `transfer(...)` function above is called with these arguments, the operator list is cleared and the owner will still have the NFT. The effect would be equivalent to that the operator successfully revokes all operators.
Disallow this behaviour and unexpected edge case from occurring by disallowing specifying the same address for `from` and `to` in the `_transfer(...)` internal function parameter.
> fix: [QSP-3] Operator Could Clear Operator List in LSP8

- contracts/LSP4DigitalAssetMetadata/LSP4DigitalAssetMetadata.sol
- contracts/LSP4DigitalAssetMetadata/LSP4DigitalAssetMetadataInitAbstract.sol
- tests/LSP7DigitalAsset/LSP7DigitalAsset.test.ts
- tests/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.behaviour.ts
- tests/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.test.ts
add requirements check in `LSP4DigitalAssetMetadata` and `LSP4DigitalAssetMetadataInitAbstract` to ensure the contract owner is not the zero address `address(0)`
Add additional tests to ensure correct behaviour of internal `_burn(...)` function from `LSP8IdentifiableDigitalAssetCore`.
> fix: [QSP-4] add requirements checks on `LSP4DigitalAssetMetadata` deployment + add tests for internal `_burn(...)` function in LSP8

- contracts/LSP10ReceivedVaults/LSP10Constants.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/Handling/TokenAndVaultHandling.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/Handling/TokenHandling.sol
- contracts/LSP1UniversalReceiver/LSP1Utils.sol
- contracts/LSP2ERC725YJSONSchema/LSP2Utils.sol
- contracts/LSP5ReceivedAssets/LSP5Constants.sol
- contracts/LSP5ReceivedAssets/LSP5Utils.sol
- contracts/LSP6KeyManager/LSP6Constants.sol
Using `bytes10` instead of `bytes12` in LSP2Utils functions and all function that uses LSP2 and making sure to have bytes2(0) as hardcoded function logic.
According to the documentation, data keys of type "Mapping" and "MappingWithGrouping" are formatted such that there are two empty bytes between the first ten bytes and the last twenty bytes. However, the versions of the functions generateMappingKey and generateMappingWithGroupingKey that use byte inputs take bytes12 for the first part of the key without ensuring that there are two empty bytes as per the specification.
> refactor: [QSP-7] Use `bytes10` instead of `bytes12` for Mapping.. KeyTypes

- contracts/LSP8IdentifiableDigitalAsset/LSP8Errors.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- tests/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.behaviour.ts
- tests/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.behaviour.ts
- Adding a check for already authorized operators, to revert when users try to add the same address as operator.
Description: Users can call the function authorizeOperator(), multiple times with the same arguments. That will also cause the same event to be emitted multiple times. 
Existing tests testing the possibility to add the same operator were switched from allow behavior to revert behavior + removing useless lines of code (adding the same address as operator)
> fix: [QSP-10] Revert when authorizing existing operators in LSP8

- contracts/LSP8IdentifiableDigitalAsset/LSP8Errors.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- tests/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.behaviour.ts
- Adding a check for non-existing operators, to revert when users try to remove a non-existing operator.
Description: When the user calls _revokeOperator() with a non-existing operator, the function will terminate successfully and with an incorrectly emitted event.
Added tests to support the new behavior.
> fix: [QSP-14] Revert when revoking non-existing operators 

- contracts/Helpers/Tokens/LSP7InitTester.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
- contracts/LSP6KeyManager/LSP6Errors.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- tests/LSP6KeyManager/tests/PermissionChangeAddPermissions.test.ts
- tests/LSP6KeyManager/tests/PermissionDeploy.test.ts
Removed most of TODO that are not relevant anymore:
- about DELEGATECALL in KeyManager
- LSP1UniversalReceiverDelegateUP
> fix: [QSP - Best Practices] clean TODO comments + add extra permission checks and support in LSP6

- contracts/LSP2ERC725YJSONSchema/LSP2Utils.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
Adding `_uncheckedIncrement(…)` to:
- `LSP2Utils.sol`
- `LSP6KeyManagerCore.sol`
- `LSP7DigitalAssetCore.sol`
- `LSP8IdentifiableDigitalAsset.sol`
- `LSP9VaultCore.sol`
As well as using the method in for loops.
> feat: [QSP - Best Practices] Use `_uncheckedIncrement(..)` for saving gas when iterating loops

- contracts/LSP6KeyManager/LSP6KeyManager.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP6KeyManager/LSP6KeyManagerInit.sol
- contracts/LSP6KeyManager/LSP6KeyManagerInitAbstract.sol
- hardhat.config.ts
- LSP6 contracts now have `pragma solidity ^0.8.5` instead of `pragma solidity ^0.8.6`.
- LSP smart contracts now will be compiled with solidity compiler version `0.8.10`.
> refactor: [QSP-11] Update the pragma version in the LSPs

- contracts/Factories/UniversalFactory.sol
- tests/Factories/UniversalFactory.test.ts
- Revert when `(msg.value > 0) && (initiliazeCallData.length == 0)` instead of refunding the amount sent to the caller.
Check added at the end of the function to save gas when doing successful contract deployment instead of adding the check at the top.
- Edit tests to support the new behavior.
> fix: [QSP - Best Practices] refactor `deployCreate2Proxy(..)` to revert instead of refund caller

- contracts/LSP7DigitalAsset/ILSP7DigitalAsset.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- Adding comments about Allowance Double-Spend Exploit in LSP7 Natspec in `authorizeOperator(..)` function.
This is just for warning, later actions to be discussed if we want to include `increaseAuthorizedAmount` function and `decreaseAuthorizedAmount` in implementation or/and specs.
> docs [QSP-9]: Add comments about Allowance Double-Spend Exploit in LSP7 Natspec

- constants.js
- contracts/LSP8IdentifiableDigitalAsset/LSP8Errors.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- tests/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.behaviour.ts
> refactor: rename custom error ~`LSP8CannotSendToFromAddress`~ -> `LSP8CannotSendToSelf`

- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/LSP6KeyManager/tests/PermissionDeploy.test.ts
Commit https://github.com/lukso-network/lsp-smart-contracts/pull/272/commits/8c89ddb0b67e858d6f543101f29d406cde6638cf introduces extra check to distinguish between CREATE/CREATE2 when reverting because the caller does not have the permission "DEPLOY".
Revert this change and simply use the revert string "DEPLOY", so to keep the custom `NotAuthorised(...)` based on the permissions, and not the operation type.
> revert: revert message between CREATE/CREATE2 for DEPLOY permission

- contracts/Custom/ClaimOwnership.sol
- contracts/Custom/IClaimOwnership.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- tests/LSP9Vault/LSP9Vault.behaviour.ts
- tests/UniversalProfile.behaviour.ts
This PR introduces a 2-step process for renouncing ownership of an LSP0ERC725UniversalProfile and LSP9Vault.
The method `renounceOwnership()` was overridden to save the the `block.number` to `_lastBlock` and confirming `renounceOwnership()` only if `_lastBlock + 100` <= `block.number` < `_lastBlock + 200`.
A new constant was added, `_delayBlocks` which defines the number of blocks to be delayed.
Tests were added to check if the desired behaviour was achieved.
> feat: [QSP-12] Add two step process for `renounceOwnership(...)` in `ClaimOwnership` contract

- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721Core.sol
Replace variable silenter with `solhint-disable` in the LSP8 contract.
> fix: Remove variable silenter in Tokens

- contracts/LSP7DigitalAsset/ILSP7DigitalAsset.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- Use `uint8` instead of `uint256` in LSP7 decimals
We don't need `uint256` for decimals, `uint8` is more than enough. With `uint8`, decimals can be used up to 255.
Most implementations use 18 as a decimal number. 
Reference PR in LIP: https://github.com/lukso-network/LIPs/pull/121
> refactor!: use `uint8` instead of `uint256` in LSP7 decimals

- constants.js
- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP7DigitalAsset/LSP7Errors.sol
- tests/LSP7DigitalAsset/LSP7DigitalAsset.behaviour.ts
🐛 **bug fix** 
A bug similar to #266 occurs in `LSP7DigitalAssetCore.sol`, when an operator makes a token transfer with the same address for `from` and `to`.
However for the same issue in LSP7: 
- the token balance of the `from` address would remain the same ✅ 
- the operator allowance would decrease by `amount`, although no tokens have actually been transferred. ❌ 🐛 
- Prevent any caller to specify the same address for `from` and `to` when doing a token transfer.
- introduce a new custom error `LSP7CannotSendToSelf`, similar to the one introduced in #278.
> fix: prevent operator allowance to decrease if `from` and `to` are the same address

- README.md
> docs: inline npm and coverage badges in README

- constants.js
- contracts/Custom/IClaimOwnership.sol
- contracts/Helpers/ERC165Interfaces.sol
- contracts/LSP0ERC725Account/LSP0Constants.sol
- contracts/LSP9Vault/LSP9Constants.sol
- tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault.test.ts
- tests/LSP7DigitalAsset/extensions/LSP7Mintable.behaviour.ts
- tests/LSP8IdentifiableDigitalAsset/extensions/LSP8Mintable.behaviour.ts
- tests/LSP9Vault/LSP9Vault.behaviour.ts
- tests/UniversalProfile.behaviour.ts
- tests/utils/fixtures.ts
- Update ClaimOwnership, LSP0 and LSP9 InterfaceId
- Add Custom error to constants.js
- Update event signatures
> refactor!: Update ClaimOwnership, LSP0 and LSP9 InterfaceId

- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/LSP1UniversalReceiverDelegateVault.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP7DigitalAsset/extensions/LSP7CappedSupplyCore.sol
- contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20Core.sol
- contracts/LSP7DigitalAsset/presets/LSP7Mintable.sol
- contracts/LSP7DigitalAsset/presets/LSP7MintableInitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CappedSupplyCore.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721Core.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8EnumerableCore.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8Mintable.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8MintableInitAbstract.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
Since solidity [0.8.8](https://github.com/ethereum/solidity/releases/tag/v0.8.8), the following language feature was introduced.
This makes most of the `override` keywords redundant since #275 upgraded the default solc compiler to 0.8.10 in `hardhat.config.ts`.
This PR cleanup the redundant and unecessary `override` modifiers, mostly for functions directly implemented from the LSP interfaces files.
> chore: remove redundant `override` keywords

- DEPLOYMENT.md
add documentation in `DEPLOYMENT.md` to explain how to verify the lsp-smart-contracts deployed on L16 using the hardhat plugin [`@nomiclabs/hardhat-etherscan`](https://hardhat.org/hardhat-runner/plugins/nomiclabs-hardhat-etherscan).
There is a small issue in the `hardhat verify` plugin reported in this issue in the Hardhat repository: https://github.com/NomicFoundation/hardhat/issues/3141
> made with @YamenMerhi 🤝
> docs: add documentation to verify contracts with hardhat plugin

- contracts/LSP9Vault/LSP9VaultCore.sol
- tests/LSP9Vault/LSP9Vault.behaviour.ts
- Overriding execute function in LSP9Vault and disallowing the use of delegatecall, since it's a dangerous operation and could lead to the destruction of the vault.
The use of delegatecall in LSP9 is totally optional. 
Referring to the [LSP9 specs](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-9-Vault.md), it's mention that an LSP9Vault must include the following operation: CALL, CREATE, CREATE2, STATICCALL and CAN include the operation DELEGATECALL.
> refactor: disallow DELEGATECALL operation in LSP9Vault

- CHANGELOG.md
- package-lock.json
- package.json
- bump version in `package.json`: `0.6.3` -> `0.7.0`
- add release notes in `CHANGELOG.md`
> chore: prepare release 0.7.0

- contracts/Custom/ClaimOwnership.sol
- tests/ClaimOwnership.behaviour.ts
This PR fixes the bug described in this [tweet](https://twitter.com/pcaversaccio/status/1569373269228142592?t=3i66r7ZBWTL6ZwWREA6MCQ&s=19). Also there is a test added to check that this behaviour is not happening.
Unwanted behaviour:
Step 1: Using `transferOwnership(..)` to set a `pendingOwner`.
Step 2: Using `renounceOwnerhisp(..)` which updates the `owner` but not the `pendingOwner`.
Step 3: Using `claimOwnership(..)` which will make `pendingOwner` the `owner`.
In this way one could renounce ownership of the contract for the public but whenever it is the most profitable the `pendingOwner` will be able to claim ownership of the contract.
To mitigate this unwanted behaviour the `pendingOwner` is reseted whenever `renounceOwnership(..)` is used.
> fix:  Reset `pendingOwner` whenever `renounceOwnership(..)` is used.

- constants.js
In the `constants.js` file, for the data key `SupportedStandards:...` under `ERC725YKeys`, specify the member `key` to only list data keys under these constants.
> fix: add reference to `.key` member for SupportedStandards in constants.js

- CHANGELOG.md
- package-lock.json
- package.json
- Bump version in `package.json` and `package-lock.json`: `0.7.0` -> `0.8.0`
- add release notes in `CHANGELOG.md`
> chore: prepare release 0.8.0

- constants.js
- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP1UniversalReceiver/ILSP1UniversalReceiver.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- tests/LSP1UniversalReceiver/LSP1UniversalReceiver.behaviour.ts
- tests/LSP9Vault/LSP9Vault.behaviour.ts
- Marking the value field as indexed
- Remove the indexed from the returnedValue
- Switch between receivedData and returnedValue parameters.
Before: 
```js
event UniversalReceiver(
address indexed from,
uint256 value,
bytes32 indexed typeId,
bytes indexed returnedValue,
bytes receivedData,
);
```
Now: 
```js
event UniversalReceiver(
address indexed from,
uint256 indexed value,
bytes32 indexed typeId,
bytes receivedData,
bytes returnedValue
);
```
Note: Event signature will not change since both switched parameters are bytes.
> refactor!: switch the returnedValue with the receivedData values in UniversalReceiver Event

- contracts/LSP6KeyManager/LSP6Errors.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/LSP6KeyManager/tests/PermissionChangeAddPermissions.test.ts
**Bug fix**
When the data key passed to the Key Manager is a key-value pair for `AddressPermissions[index]`, the current behaviour is that the caller/signer must have the permission `CHANGE PERMISSION`.
Add additional check to verify what is stored under this type of data key in the storage.
- if some value are set under `AddressPermissions[index]` = caller must have permission `CHANGE PERMISSION`.
- if no value is set under `AddressPermissions[index]` = caller must have permission `ADD PERMISSION`.
> fix: add checks for ADD / CHANGE permissions when data key is `AddressPermissions[index]`

- constants.js
- contracts/LSP14Ownable2Step/LSP14Ownable2Step.sol
- tests/LSP14Ownable2Step/LSP14Ownable2Step.behaviour.ts
This PR add the `OwnershipRenounced()` event:
- In the LSP14 contract at the end of `renounceOwnership()`
- In the constants.js file
Also there is a test added for checking if the event is emitted whenever the process of renouncing ownership of the contract is confirmed.
> feat: Add `OwnershipRenounced()` event as mentioned in the specs.

- contracts/Helpers/UPWithInstantAcceptOwnership.sol
- tests/LSP14Ownable2Step/LSP14Ownable2Step.behaviour.ts
This PR creates a UP contract for testing, with a modified `universalReceiver(..)` which calls `acceptOwnership(..)` whenever the `universalReceiver(..)` is called with the specific typeId used to notify the new owner that he can accept ownership of a contract.
A new test is introduced that should make sure that the transaction is reverted whenever someone calls `trasferOwnership(..)` and `acceptOwnership(..)` is executed in the same block.
> test: Add test for verifying that one cannot use `acceptOwnership` in the same trx as `transferOwnership`

- contracts/Helpers/ABIEncoder.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- tests/Helpers/ABIEncoder.test.ts
- tests/LSP1UniversalReceiver/LSP1UniversalReceiver.behaviour.ts
- tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP.behaviour.ts
- tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault.behaviour.ts
- tests/LSP9Vault/LSP9Vault.behaviour.ts
- Adding routing to the universalReceiver function
- Add tests to check how ABI encoding works and gas costs
- Resolve test according to new behaviour
> feat: add routing (= external call ) to additional contract in `universalReceiver(...)` function based on typeId

- constants.js
- contracts/LSP14Ownable2Step/LSP14Constants.sol
- contracts/LSP7DigitalAsset/LSP7Constants.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8Constants.sol
- tests/LSP7DigitalAsset/LSP7DigitalAsset.behaviour.ts
- tests/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.behaviour.ts
- construct typeIds based on mapping keyType
- Update the typeIds in constant.js
- Remove hardoced constant in tests
TypeIds now are constructed as Mapping KeyType according to LSP2-ERC725YJSONSchema 
The usage of typeId in mapping form will make it more easy to identify which Keys and Values being set in the ERC725Y storage are relevant to a typeId based on the 10bytes prefix. 
This will also allow KeyManagers in the future to implement specific permission to set these kind of keys based on the fixed bytes10 prefix.
> refactor: construct typeIds based on mapping keyType

- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
This PR separates the `fallback()` and `receive()` functions for the safe of separating the concern in LSP0 & LSP9: 
- receiving data (arbitrary or not) with no value -> `fallback()`
- receiving data (arbitrary or not) with value -> `fallback()`
- receiving just value with no data -> `receive()`
> refactor: Separate `fallback()` and `receive()` functions in LSP0 & LSP9

- constants.js
- contracts/Helpers/UniversalReceivers/UniversalReceiverDelegateRevert.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP14Ownable2Step/LSP14Constants.sol
- contracts/LSP1UniversalReceiver/LSP1Constants.sol
- contracts/LSP7DigitalAsset/LSP7Constants.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8Constants.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- tests/LSP1UniversalReceiver/LSP1UniversalReceiver.behaviour.ts
- tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP.behaviour.ts
- tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault.behaviour.ts
- tests/LSP7DigitalAsset/LSP7DigitalAsset.behaviour.ts
- tests/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.behaviour.ts
- tests/LSP9Vault/LSP9Vault.behaviour.ts
- tests/UniversalProfile.test.ts
- Reverting the changes of the typeId
- Updating the logic of the universalReceiver so it constructs the Key of the typeId delegate from the typeId received.
> fix: update the logic inside universalReceiver function and revert typeId changes

- constants.js
- contracts/LSP14Ownable2Step/LSP14Ownable2Step.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/LSP6KeyManager/tests/PermissionDeploy.test.ts
In the LSP14Ownable2Step, the function `transferOwnership(...)` performs 3 steps that are similar to the check-effect-interaction pattern.
1. **check** -> validate the required inputs provided as arguments (the `newOwner` is not the address of the contract itself).
2. **effect** -> perform write operations on the contract and blockchain state.
2.a) set up the  `pendingOwner` as the `newOwner`.
2.b) emit an event `OwnershipTransferStarted` which write to the blockchain logs.
3. **interactions** -> if the pending owner is a contract that implements the LSP1, notify the pending owner through an **external call** to its `universalReceiver(...)` function.
Written in this order, the steps appear to follow clearly the check-effect-interaction pattern in the right order. However, in the current …
> fix: emit `OwnershipTransferStarted` and `Executed` events before external calls

- contracts/LSP10ReceivedVaults/LSP10Utils.sol
- contracts/LSP5ReceivedAssets/LSP5Utils.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP6KeyManager/LSP6Utils.sol
- contracts/LSP7DigitalAsset/LSP7Errors.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8Errors.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
In this PR we add some natspec in the following contracts:
- LSP5Utils.sol
- LSP6KeyManagerCore.sol
- LSP6Utils.sol
- LSP7Errors.sol
- LSP8IdentifiableDigitalAssetCore.sol
- LSP8Errors.sol
- LSP10Utils.sol
> docs: update smart contracts natspec

- contracts/Custom/ERC165Checker.sol
> fix: [WP-M4] avoid "returnbomb" in ERC165Checker

- contracts/LSP2ERC725YJSONSchema/LSP2Utils.sol
- tests/LSP2ERC725YJSONSchema/LSP2UtilsLibrary.test.ts
The function `isEncodedArray(...)` in `LSP2Utils` behaves incorrectly when the input argument is a bytes32 long value:
e.g:
- any `uint256` value (e.g: **32**, **12345**, ...)
- any `bytes32` value
This causes the function to revert with the following error.
This error originates from the `solidity-bytes-utils` library: https://github.com/GNSPS/solidity-bytes-utils/blob/6458fb2780a3092bc756e737f246be1de6d3d362/contracts/BytesLib.sol#L375
This PR fixes this behaviour.
> fix: [WP-M9] LSP-2: `LSP2Utils.isEncodedArray()` Incomplete implementation

- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
In the Key Manager, the `mask` to calculate the dynamic part of the allowed ERC725Y data key to check is calculated on every iteration in the inner `for` loop (loop that iterates over the input data keys).
Move the mask calculation one level up, outside of the inner `for` loop to save gas. This reduce:
- deployment cost by 626 gas
- runtime cost by 63 gas
> perf: [WP-M24] LSP-6: Recalculate the same `mask` in the for loop is unnecessary

- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/LSP1UniversalReceiverDelegateVault.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP7DigitalAsset/LSP7Errors.sol
- tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP.behaviour.ts
- tests/LSP7DigitalAsset/LSP7DigitalAsset.behaviour.ts
In this PR:
- We allow zero-value transfers, mints and burns in LSP7
- We introduce a check in LSP1 that verifies if the recipient's balance is updated, in order to register a new asset
> fix: [WP-M8] LSP7 allow zero-value transfers for `transfer(..)`, `mint(..)` and `burn(..)`

- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/LSP6KeyManager/tests/PermissionChangeAddPermissions.test.ts
Allow controller addresses to clear addresses under `AddressPermissions[index]`.
Co-authored-by: b00ste.lyx <b00ste@users.noreply.github.com>
> fix: [WP-M6] LSP-6: `_PERMISSION_CHANGEPERMISSIONS` should be able to delete a AddressPermissions[index]

- contracts/Helpers/TargetContract.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/LSP6KeyManager/LSP6KeyManager.behaviour.ts
- tests/LSP6KeyManager/tests/AllowedFunctions.test.ts
- tests/LSP6KeyManager/tests/ExecuteRelayCall.test.ts
- tests/LSP6KeyManager/tests/MultiChannelNonce.test.ts
- tests/LSP6KeyManager/tests/PermissionCall.test.ts
- tests/LSP6KeyManager/tests/PermissionDeploy.test.ts
- tests/LSP6KeyManager/tests/Security.test.ts
- tests/LSP6KeyManager/tests/index.ts
> feat: [WP-H2] Add msg.value to LSP6 signed message

- constants.js
- contracts/Helpers/KeyManager/KeyManagerInternalsTester.sol
- contracts/LSP2ERC725YJSONSchema/LSP2Errors.sol
- contracts/LSP2ERC725YJSONSchema/LSP2Utils.sol
- contracts/LSP6KeyManager/LSP6Constants.sol
- contracts/LSP6KeyManager/LSP6Errors.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/LSP6KeyManager/internals/AllowedERC725YKeys.internal.ts
- tests/LSP6KeyManager/tests/AllowedERC725YKeys.test.ts
- tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
- tests/LSP6KeyManager/tests/PermissionChangeAddPermissions.test.ts
- tests/LSP6KeyManager/tests/PermissionSetData.test.ts
- tests/utils/fixtures.ts
- tests/utils/helpers.ts
- Change in how we store the: `AllowedERC725YKeys` in the ERC725Y storage:
- before: `bytes32[] encoded array`
- now: `compactedBytesArray` 
- Change in how we check the `AllowedERC725YKeys` in the LSP6KeyManager according to `compactedBytesArray` type.
- Add new custom error to `constant.js`
> refactor!: [WP-C2] Change the verification logic of AllowedERC725YKeys in LSP6

- contracts/LSP6KeyManager/LSP6Errors.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/LSP6KeyManager/internals/AllowedCalls.internal.ts
- tests/LSP6KeyManager/tests/AllowedAddresses.test.ts
- tests/LSP6KeyManager/tests/AllowedFunctions.test.ts
- tests/LSP6KeyManager/tests/ExecuteRelayCall.test.ts
- tests/LSP6KeyManager/tests/PermissionCall.test.ts
- tests/LSP6KeyManager/tests/PermissionChangeAddPermissions.test.ts
- tests/LSP6KeyManager/tests/PermissionDelegateCall.test.ts
- tests/LSP6KeyManager/tests/PermissionSetData.test.ts
- tests/LSP6KeyManager/tests/PermissionStaticCall.test.ts
- tests/LSP6KeyManager/tests/PermissionTransferValue.test.ts
- tests/LSP6KeyManager/tests/Security.test.ts
- tests/LSP7DigitalAsset/extensions/LSP7Mintable.behaviour.ts
- tests/LSP8IdentifiableDigitalAsset/extensions/LSP8Mintable.behaviour.ts
Change the behaviour of the permissions `TRANSFER_VALUE`, `CALL` and `STATICCALL` to not allow any interaction if nothing is set under `AllowedCall`.
> fix!: [WP-M7] LSP-6: do not allow any interaction if `AllowedCalls` is empty for a caller/signer

- contracts/LSP0ERC725Account/LSP0ERC725AccountInit.sol
- contracts/LSP6KeyManager/LSP6KeyManagerInit.sol
- contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20MintableInit.sol
- contracts/LSP7DigitalAsset/presets/LSP7MintableInit.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8CompatibleERC721MintableInit.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8MintableInit.sol
- contracts/LSP9Vault/LSP9VaultInit.sol
- contracts/UniversalProfileInit.sol
Change the visibility of the `initialize(...)` functions from `public` to `external` to make it behave more like a `constructor` (since constructor are only called externally on deployment).
This also prevent calling the `initialize(...)` internally by mistake when the `Init` contracts are used via inheritance.
Finally, this enables to **"open-up** the visibility/scope of the function via overriding, as it is not possible to "close-down/restrict" the visibility at the moment because of the current Solidity behaviour. See this issue on the OpenZeppelin repository for more details: https://github.com/OpenZeppelin/openzeppelin-contracts/issues/3750
> refactor!: mark `initialize(...)` functions as `external`

- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- tests/LSP9Vault/LSP9Vault.behaviour.ts
- tests/UniversalProfile.behaviour.ts
- An additional check made in the receive function to ensure that `msg.value` is greater than 0, then we emit the event.
If not the event will not be emitted and the call should go through.
In solidity, if both `receive` and `fallback` function are implemented, and the contract receive an empty call `{value: 0, data: "0x"}`, the call goes to the `receive` function. 
We emit `ValueReceived` in `receive` without checking that msg.value is greater than 0.
Emit  `ValueReceived` in `receive` only when `msg.value > 0`
> fix: add check for ValueReceived event in LSP0/LSP9

- contracts/LSP6KeyManager/LSP6Errors.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/LSP6KeyManager/tests/AllowedERC725YKeys.test.ts
- tests/LSP6KeyManager/tests/PermissionChangeAddPermissions.test.ts
- Optimising `_verifyAllowedERC725YKeys` so it is more gas efficient.
- Disallow `bytes32(0)` data key to be set a data value through the LSP6KeyManager, for security reasons.
- Properly test that one is not allowed to use `setData(bytes32,bytes)` & `setData(bytes32[],bytes[])` if one of the input data keys is equal to `bytes32(0)`.
> refactor: optimise `_verifyAllowedERC725YKeys` and properly test bytes32(0) key

- contracts/Factories/UniversalFactory.sol
- tests/Factories/UniversalFactory.test.ts
( In case of {deployCreate2} if the contract is initializable the `msg.value` now goes to the external call, not the contract creation )  
When deploying a normal contract using `deployCreate2(..)`, wether the contract is initializable or not, the `msg.value` passed was directly sent to the creation of the contract, which means to the constructor that needs to be payable.
And if the contract is initializable, there is no possibility to send value along calling the supposed `initialize(..)` function.
Most valid cases where the contract is initializable, the value needs to be send to the initialize function not the constructor. 
If the normal contract to deploy using `deployCreate2(..)`  is not initializable, we pass the `msg.value` to the contract creation (constructor), if it's …
> refactor: add `ContractCreated` event and refactor UniversalFactory contract

- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
- tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP.behaviour.ts
In this PR we introduce a check inside LSP1’s function, `universalReceiverDelegate(..)` that checks for the LSP9 interface id in order to differentiate between ownership transfers of an LSP9 and an LSP0
> refactor: Add a way to differentiate LSP0 from LSP9 inside the `universalReceiverDelegate(..)` of the LSP1

- contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.sol
- contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20InitAbstract.sol
- tests/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.behaviour.ts
- tests/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.test.ts
This PR fixes the following issue ⬇️ 
Update the current behaviour of the LSP7CompatibleERC20 and LSP7CompatibleERC20Init to reflect this behaviour.
emit `Approval` event in the following circumstances:
This was implemented by overriding the behaviour of `_updateOperator` from LSP7DigitalAssetCore, as mentioned in the suggestions.
> ### ℹ️ **Notice**
> The screenshot above suggests to implement the `Approval` event in the internal `_burn` function. This was not implemented for the following reason.
>
> In the OpenZeppelin implementation, the `Approval` event is implemented on the public [`burnFrom`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/afb20119b33072da041c97ea717d3ce4417b5e01/contracts/token/ERC20/extensions/ERC20Burnable.sol#L36) function, not on the internal …
> fix: [WP-L11] LSP-7: LSP7CompatibleERC20 is not fully compatible with the conventional implementation of ERC20 on the emission of `Approval` events

- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- tests/LSP9Vault/LSP9Vault.behaviour.ts
- tests/LSP9Vault/LSP9Vault.test.ts
- tests/UniversalProfile.behaviour.ts
- tests/UniversalProfile.test.ts
**In LSP0 and LSP9.**
Emit the `ValueReceived` event when caller send some value while calling the new batch `execute(uint256[],address[],uint256[],bytes[])` function from ERC725X.
This was missed in #355
> fix: add `ValueReceived` event to batch ERC725X `execute(uint256[],address[],uint256[],bytes[])` functions in LSP0 and LSP9

- constants.js
- contracts/LSP6KeyManager/ILSP6KeyManager.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
For LSP6KeyManager `Executed` event:
- change the order of the parameters emitted by the `Executed` event.
- mark both parameters as `indexed`.
- update the event signature under `constants.js`
**Before**
```
event Executed(uint256 indexed value, bytes4 selector);
```
**Now**
```
event Executed(bytes4 indexed selector, uint256 indexed value);
```
> refactor!: switch the order of LSP6 `Executed` event + index both params

- contracts/LSP1UniversalReceiver/LSP1Errors.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/LSP1UniversalReceiverDelegateVault.sol
- tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP.behaviour.ts
Add a check that prevents calling `universalReceiver(...)` function with a value associated
> refactor: prevent calling universalReceiver(...) with value

- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
When running Slither against `LSP7DigitalAssetCore` or `LSP8IdentifiableDigitalAssetCore`, the following errors are reported ⬇️ .
In brief, Slither spots some [potential costly operations inside a loop](https://github.com/crytic/slither/wiki/Detector-Documentation#costly-operations-inside-a-loop): the `for` loop of the `transferBatch` function.
This error is a false positive, as the **costly operations inside a loop** here refer to increasing/decreasing the total supply of `_existingTokens`, via the `_beforeTokenTransfer` hook. However, this will never happen as there will not be any token supply increase or decrease on any transferBatch, because neither `from` nor `to` can be `address(0)`. Only the functions `_mint(...)` and `_burn(...)` can increase/decrease the total supply.
This …
> Fix Slither error for `transferBatch` in LSP7/8 + remove logic of `_beforeTokenTransfer` hooks

- contracts/Helpers/ABIEncoder.sol
- contracts/Helpers/FallbackExtensions/OnERC721ReceivedExtension.sol
- contracts/Helpers/FallbackExtensions/ReenterAccountExtension.sol
- contracts/Helpers/Reentrancy/ReentrancyWithAddPermission.sol
- contracts/Helpers/Reentrancy/ReentrancyWithAddURD.sol
- contracts/Helpers/Reentrancy/ReentrancyWithChangePermission.sol
- contracts/Helpers/Reentrancy/ReentrancyWithChangeURD.sol
- contracts/Helpers/Reentrancy/ReentrancyWithSetData.sol
- contracts/Helpers/Reentrancy/ReentrancyWithValueTransfer.sol
- contracts/Helpers/Reentrancy/RelayReentrancy.sol
- contracts/Helpers/Security/Reentrancy.sol
- contracts/Helpers/SignatureValidatorContract.sol
- contracts/Helpers/UPWithInstantAcceptOwnership.sol
- contracts/Helpers/UniversalReceivers/UniversalReceiverDelegateDataUpdater.sol
- contracts/Helpers/UniversalReceivers/UniversalReceiverDelegateRevert.sol
- contracts/Helpers/UniversalReceivers/UniversalReceiverDelegateVaultReentrantA.sol
- contracts/Helpers/UniversalReceivers/UniversalReceiverDelegateVaultReentrantB.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/LSP1UniversalReceiverDelegateVault.sol
- contracts/LSP2ERC725YJSONSchema/LSP2Utils.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721InitAbstract.sol
- contracts/Legacy/UniversalReceiverAddressStore.sol
- tests/LSP6KeyManager/tests/Security.test.ts
There is currently a lot of warnings generated by the solc compiler. These come from contracts in various places in the repository, including:
- many Helpers contracts
- `LSP1UniversalReceiverDelegateUP`.
- `LSP1UniversalReceiverDelegateUP`.
- the function `isCompactBytesArray` in `LSP2Utils.sol`.
- `LSP8IdentifiableDigitalAssetCore`
This PR introduces changes that fix all the compiler warnings.
In some functions of these two contracts, some function parameters were not used. For instance.
- `data` in `LSP1UniversalReceiverDelegateUP`.
- `tokenId` in the `_beforeTokenTransfer` hook of LSP8.
See screenshot below for LSP1DelegateUP.
**These warnings are made silent now using the following.**
After analysis, this syntax silent warning and is safe as it does not push any new item on the …
> fix: all `solc` compiler warnings

- contracts/LSP9Vault/LSP9VaultInit.sol
- tests/Helpers/ABIEncoder.test.ts
- tests/LSP14Ownable2Step/LSP14Ownable2Step.behaviour.ts
- tests/LSP1UniversalReceiver/LSP1UniversalReceiver.behaviour.ts
- tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP.behaviour.ts
- tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP.test.ts
- tests/LSP2ERC725YJSONSchema/LSP2UtilsLibrary.test.ts
- tests/LSP6KeyManager/LSP6KeyManager.behaviour.ts
- tests/LSP6KeyManager/LSP6KeyManager.test.ts
- tests/LSP6KeyManager/internals/AllowedCalls.internal.ts
- tests/LSP6KeyManager/internals/ReadPermissions.internal.ts
- tests/LSP6KeyManager/tests/AllowedAddresses.test.ts
- tests/LSP6KeyManager/tests/AllowedFunctions.test.ts
- tests/LSP6KeyManager/tests/AllowedStandards.test.ts
- tests/LSP6KeyManager/tests/BatchExecute.test.ts
- tests/LSP6KeyManager/tests/ExecuteRelayCall.test.ts
- tests/LSP6KeyManager/tests/OtherScenarios.test.ts
- tests/LSP6KeyManager/tests/PermissionChangeAddPermissions.test.ts
- tests/LSP6KeyManager/tests/PermissionChangeOwner.test.ts
- tests/LSP6KeyManager/tests/PermissionDelegateCall.test.ts
- tests/LSP6KeyManager/tests/PermissionSetData.test.ts
- tests/LSP6KeyManager/tests/PermissionStaticCall.test.ts
- tests/LSP6KeyManager/tests/PermissionTransferValue.test.ts
- tests/LSP6KeyManager/tests/Reentrancy.test.ts
- tests/LSP6KeyManager/tests/Security.test.ts
- tests/LSP9Vault/LSP9Vault.behaviour.ts
- tests/LSP9Vault/LSP9Vault.test.ts
- tests/UniversalProfile.behaviour.ts
- tests/UniversalProfile.test.ts
- tests/utils/context.ts
This PR concerns the following test suites:
- LSP3
- LSP6 (**mainly**)
These test suites take a lot of time to run in the CI, in particular LSP6. See screenshot below.
Improve the speed of these tests, using the following 2 techniques:
- replace `beforeEach` hooks by `before` hooks: avoid heavy setup on every single tests (deploying a UP, deploying a KeyManager, setting the permissions + link to a default LSP1UniversalReceiverDelegate, transferring ownership to the Key Manager, etc...)
- avoid sending separate transactions in the setup of the `before` hooks to fund the UP with LYX (for tests that require native LYX tokens transfers. Fund the UP immediately on deployment).
> test: improve speed for running tests from LSP3 + LSP6 test suites.

- contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.sol
- contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20InitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721InitAbstract.sol
- hardhat.config.ts
When compiling with Solidity version 0.8.13, the compiler produces the following errors:
```
TypeError: Derived contract must override function "supportsInterface". Two or more base classes define function with same name and parameter types.
--> contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.sol:16:1:
|
16 | abstract contract LSP7CompatibleERC20 is ILSP7CompatibleERC20, LSP4Compatibility, LSP7DigitalAsset {
| ^ (Relevant source part starts here and spans across multiple lines).
Note: Definition in "ERC725YCore": 
--> @erc725/smart-contracts/contracts/ERC725YCore.sol:101:5:
|
101 |     function supportsInterface(bytes4 interfaceId)
|     ^ (Relevant source part starts here and spans across multiple lines).
Note: Definition in "LSP7DigitalAsset": 
--> …
```
> fix: Add appropriate overrides of supportsInterface in LSP7 and LSP8

- contracts/Helpers/ERC165/NoSupportsInterfaceWithFallback.sol
- contracts/Helpers/ERC165/NoSupportsInterfaceWithoutFallback.sol
- contracts/Helpers/ERC165/SupportsInterfaceOnlyERC165.sol
- contracts/Helpers/ERC165/SupportsInterfaceOnlyLSP0.sol
- contracts/Helpers/ERC165/SupportsInterfaceRevert.sol
- tests/Helpers/ERC165CheckerCustom.test.ts
- Adding more tests to ERC165CheckerCustom.
- Identify unexpected behavior pointed by Lucas from RV and confirm the case with tests.
- When we call `supportsERC165Interface(address account, bytes4 interfaceId)` on an `account` that supports `interfaceId` via ERC165 it should return true. When the `account` doesn't support `interfaceId` it should return false.
- When we call `supportsERC165Interface(address account, bytes4 interfaceId)` on the following precompiled adresses as `account`:  
- `0x0000000000000000000000000000000000000002`  
- `0x0000000000000000000000000000000000000003`
- `0x0000000000000000000000000000000000000004`    
it's always returning true regardless of the interfaceId (Checked 1000 interfaceIds).
> test: add more tests to custom ERC165CheckerCustom

- contracts/Helpers/FallbackExtensions/ERC165Extension.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP17ContractExtension/LSP17Extendable.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- tests/LSP17ContractExtension/LSP17Extendable.behaviour.ts
- Adding to LSP0/9 the possibility of supporting an interface through the ERC165Extension.
- Since we implemented Fallback extensions in LSP0, now we can call functions on the LSP0 that are not existing as part of the core code but as extensions, but adding functions as extensions is not enough since some application check InterfaceId before calling. (For example in our `universalReceiver(..)` function we check LSP1 interfaceId before calling the function)
To avoid situations where we implement a new function as extension but we miss supporting the interfaceId, we decided to check if there is more interfaceIds supported in the ERC165Extension whenever someone calls the `supportsInterface(..)` function of the LSP0/LSP9
The `supportsInterface(..)` on LSP0 will return true if only called …
>  feat!: adjust supportsInterface in LSP0/9 to support Interfaces of ERC165Extension

- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
Avoid re-assigning `_reentrancyStatus = _ENTERED` when `_reentrancyStatus` is already equal to `_ENTERED`
> refactor: optimise _reentrancyStatus on reentrancy

- contracts/LSP6KeyManager/LSP6Errors.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/LSP6KeyManager/internals/AllowedERC725YDataKeys.internal.ts
Added check that makes sure the length of a dynamic key is not superior to 32 in order to avoid overflow.
> refactor: add length check in verifyAllowedERC725YSingleKey

- contracts/LSP2ERC725YJSONSchema/LSP2Utils.sol
`generateArrayKey(...)` would underflow if the length of the string passed was smaller than 2 characters.
> refactor: add length check generateArrayKey(...)

- contracts/LSP10ReceivedVaults/LSP10Utils.sol
- contracts/LSP5ReceivedAssets/LSP5Utils.sol
In this PR a getter is introduced in both `LSP5Utils` and `LSP10Utils`:
- In `LSP5Utils` for getting the length of the array of `ReceivedAssets`
- In `LSP10Utils` for getting the length of the array of `ReceivedVaults`
> refactor: add new utility methods in LSP5Utils and LSP10Utils

- contracts/LSP14Ownable2Step/LSP14Ownable2Step.sol
In this PR we remove an unnecessary SLOAD by changing `_setOwner(_pendingOwner);` to `_setOwner(msg.sender);`
```solidity
function _acceptOwnership() internal virtual {
require(msg.sender == pendingOwner(), "LSP14: caller is not the pendingOwner");
address previousOwner = owner();
_setOwner(msg.sender);
[...]
}
```
> refactor: [WP-G21] LSP-14: Unnecessary SLOAD

- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/LSP1UniversalReceiverDelegateVault.sol
This PR an external call check:
```solidity
// if the amount sent is 0, then do not update the keys
uint256 balance = ILSP7DigitalAsset(notifier).balanceOf(msg.sender);
if (balance == 0) return "LSP1: balance not updated";
```
is moved after this check:
```solidity
// if the map value is already set, then do nothing
if (bytes12(notifierMapValue) != bytes12(0))
return "URD: asset received is already registered";
```
in order to save some gas in some situations, because the external calls are quite expensive.
> refactor: [WP-G22] LSP-1: Check the `notifierMapValue` first can save gas

- constants.js
- contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
- contracts/LSP14Ownable2Step/LSP14Ownable2Step.sol
- tests/LSP14Ownable2Step/LSP14Ownable2Step.behaviour.ts
This PR updates the name of the event `RenounceOwnershipInitiated()` to `RenounceOwnershipStarted()` according to the specs of [LSP14](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-14-Ownable2Step.md#renounceownershipstarted)
> refactor: [WP-D19] Change event `RenounceOwnershipInitiated` to `RenounceOwnershipStarted` in LSP14

- .github/workflows/benchmark.yml
- .gitignore
- tests/Benchmark.test.ts
add gas benchmark tests for common scenarios for `execute(...)` to keep track of the gas usage.
_Examples:_
- transferring LYX from a UP to an EOA.
-  transferring LYX to from a UP to an other UP.
- sending tokens (LSP7) from a UP.
- transferring ownership of a specific from a UP to an other UP.
Currently, the Gas Benchmark CI runs on every single approval. This clutters the email box with Github notifications from the bot.
Edit the workflow to run the workflow only once on the first approval of the PR.
👋 Hello
⛽ I am the Gas Bot Reporter. I keep track of the gas costs of common interactions using Universal Profiles 🆙 !
📊 Here is a summary of the gas cost with the code introduced by this PR.
<details>
<summary>⛽📊 See Gas Benchmark report</summary>
This document contains the gas usage for …
> test: add gas benchmark reports for `execute(...)` scenarios via Key Manager + run Benchmark CI only on first approval

- contracts/LSP17ContractExtension/LSP17Extendable.sol
- Improve natspec in LSP17Extendable by:
- explicitly documenting that `_fallbackLSP17Extendable()` should be called at the end of the `fallback()` function.
- add usecase of `_supportsInterfaceInERC165Extension()` function
> docs: [WP-D17] Improve Natspec in LSP17Extendable

- contracts/LSP14Ownable2Step/LSP14Ownable2Step.sol
This PR changes the visibility of the following constants from private to public:
- `RENOUNCE_OWNERSHIP_CONFIRMATION_DELAY`
- `RENOUNCE_OWNERSHIP_CONFIRMATION_PERIOD`
> refactor: [WP-I20] LSP-14 Make time-related constants public

- contracts/LSP2ERC725YJSONSchema/LSP2Utils.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/Mocks/LSP2UtilsLibraryTester.sol
- tests/LSP2ERC725YJSONSchema/LSP2UtilsLibrary.test.ts
> [WP-M1] LSP-2: `LSP2Utils.isCompactBytesArray(bytes)` Empty array (`[]`) will return `false`

- contracts/LSP14Ownable2Step/LSP14Ownable2Step.sol
- tests/LSP14Ownable2Step/LSP14Ownable2Step.behaviour.ts
In the PR the process of transferring ownership is canceled when the process of renouncing ownership is started and vice-versa.
> refactor: make LSP14 processes cancel each other.

- constants.js
- contracts/LSP6KeyManager/LSP6Errors.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/LSP6KeyManager/tests/OtherScenarios.test.ts
- tests/LSP6KeyManager/tests/PermissionCall.test.ts
In this PR the following changes are made:
- A new error added, 'InvalidPayload(bytes)'.
- A check added in both internal function, `` and `` in order to verify that the payload is not smaller than 4 bytes.
> refactor: add check for the payload length in `LSP6KeyManagerCore`

- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
- refactor `_validateCallerViaKeyManager` in LSP1DelegateUP in a way that the call to check the `target` in LSP6 will only happen if the owner of the UP supports LSP6.
> chore: refactor `_validateCallerViaKeyManager` in LSP1DelegateUP

- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/Mocks/GenericExecutor.sol
- contracts/Mocks/MaliciousERC1271Wallet.sol
- tests/UniversalProfile.behaviour.ts
- Remove the need to check for supportsInterface in `isValidSignature(..)` .
- Handle the call of `isValidSignature(..)` in a way that the check will not revert in case the function do not exist or the function return an unintended value. Instead just return failure value
- Unify the naming, use `isValidSignature.selector` instead of `InterfaceId`. 
- Use `code.length > 0` instead of `isContract(..)`
- Adjust the LSP0 tests to do the intended behavior of checking the signature (remove todo)
- Add tests for malicious behavior
> refactor: refactor LSP0 `isValidSignature(..)` to low level call 

- contracts/LSP2ERC725YJSONSchema/LSP2Utils.sol
- contracts/LSP6KeyManager/LSP6Utils.sol
- foundry.toml
- tests/LSP2ERC725YJSONSchema/LSP2UtilsLibrary.test.ts
- tests/foundry/LSP2ERC725YJSONSchema/LSP2Utils.t.sol
- tests/foundry/LSP6KeyManager/LSP6Utils.t.sol
> refactor: replace > by >=

- constants.js
- contracts/LSP9Vault/LSP9Errors.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- contracts/Mocks/UniversalReceivers/UniversalReceiverDelegateVaultMalicious.sol
- tests/LSP9Vault/LSP9Vault.behaviour.ts
- Refactoring the modifier to a internal function that allow the Owner and the reentrant UniversalReceiverDelegate to setData on the vault
- Add requirement in the setData functions when the URD is the one setting data, to not set LSP1/6/17 Data keys
- Add test suites to cover all scenarios possible
> refactor: [WP-D11] restrict UniversalReceiverDelegate to set LSP1/6/17 DataKeys

- contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryInit.sol
- contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryInitAbstract.sol
- contracts/LSP6KeyManager/LSP6KeyManagerInitAbstract.sol
- contracts/Mocks/ImplementationTester.sol
- package-lock.json
- package.json
- remappings.txt
Also bumped the @openzepplin versions for parity
> fix: Use @openzeppelin/contracts-upgradeable for Initializable imports

- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/LSP6KeyManager/tests/AllowedAddresses.test.ts
In `verifyAllowedCalls` we are looping over the allowedCalls array twice, once to make sure it is a valid allowedCalls and once to verify if the caller has the allowedCall permission.
Since we are checking the validity of the compact bytes array when setting the allowedCalls, in the vast majority of the case this will just be a waste of gas that can get expensive when the allowedCalls compact byte array get big.
> refactor: remove isCBACheck

- remappings.txt
One more tiny fix to remappings to support git modules in downstream projects
> fix: Narrower remapping of erc725 to support git modules downstream

- contracts/Mocks/NonPayableFallback.sol
- foundry.toml
- package.json
- tests/foundry/LSP11BasicSocialRecovery/LSP11Mock.sol
- tests/foundry/LSP16UniversalFactory/LSP16Mock.sol
- tests/foundry/LSP16UniversalFactory/LSP16UniversalProfile.t.sol
Fuzzing tests for LSP16: 
While checking for the above properties, we are also checking the LSP16 works properly and that contracts are being deployed
> test: add fuzzing test to LSP16

- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721InitAbstract.sol
- contracts/Mocks/Tokens/LSP8CompatibleERC721Tester.sol
- contracts/Mocks/Tokens/TokenReceiverWithLSP1WithERC721Received.sol
- contracts/Mocks/Tokens/TokenReceiverWithLSP1WithERC721ReceivedInvalid.sol
- contracts/Mocks/Tokens/TokenReceiverWithLSP1WithERC721ReceivedRevert.sol
- contracts/Mocks/Tokens/TokenReceiverWithoutLSP1WithERC721Received.sol
- contracts/Mocks/Tokens/TokenReceiverWithoutLSP1WithERC721ReceivedInvalid.sol
- contracts/Mocks/Tokens/TokenReceiverWithoutLSP1WithERC721ReceivedRevert.sol
- tests/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.behaviour.ts
- tests/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.test.ts
In `LSP8CompatibleERC721` and `LSP8CompatibleERC721Init`:
- when `to` is an EOA = ✅ pass  
- when `to`  is a contract that supports + implement LSP1 
- but does not implement `onERC721Received` = ❌ fail and revert  
- if it also implements `onERC721Received`, but the function `onERC721Received` reverts = ❌ fails and revert  
- if it also implements `onERC721Received` , but the function `onERC721Received`  does not return the right bytes value = ❌ fails and revert  
- if it also implements `onERC721Received` = ✅ pass  
- when `to` is a contract that does not supports LSP1
- but does not implement `onERC721Received` = ❌ fail and revert  
- if it also implements `onERC721Received` , but the function `onERC721Received` reverts = ❌ fails and revert  
- if it also implements `onERC721Received` …
> fix: [WP-I6] add `onERC721Received` check for the `safeTransferFrom` functions of `LSP8CompatibleERC721` contracts

- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- tests/LSP17ContractExtension/LSP17Extendable.behaviour.ts
- Changing the logic of handling the `bytes4(0)` sig when called to LSP0 and LSP9.
Whenever the contract was called with any data that starts with `bytes4(0)` it would emit `ValueReceived` event if native token was received and then return (ending execution).
Whenever the contract was called with any data that starts with `bytes4(0)` it would emit `ValueReceived` event if native token was received and check if there is extension set for `bytes4(0)`, if there is an extension set then forward the call to the extension, if not then return (ending execution).
The only difference between `bytes4(0)` and the other selectors is that in case the contract was called with a function selector that doesn't have an extension set it would usually revert, but when the contract is called with `bytes4(0)` …
> refactor: Support Extension for `bytes4(0)` sig in LSP0-LSP9

- CHANGELOG.md
- package-lock.json
- package.json
- bump version in `package.json` from 0.8.0 --> 0.8.1
- add details of release 0.8.1 in CHANGELOG
> chore: prepare release 0.8.1

- .github/workflows/deploy-verify.yml
- scripts/ci/check-deployer-balance.ts
- scripts/ci/deploy-verify.sh
See the CI job for an example.
https://github.com/lukso-network/lsp-smart-contracts/actions/runs/4241483646/jobs/7371788527
> ci: check deployer balance before deploy + verify contracts

- constants.ts
- contracts/LSP10ReceivedVaults/LSP10Utils.sol
- contracts/LSP5ReceivedAssets/LSP5Utils.sol
- tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP.behaviour.ts
- tests/utils/fixtures.ts
This is to prevent a `Panic(uint256)` error type with error code `0x11` due to arithmetic overflow with `max(uint128) + 1`
This PR follows the changes introduced in the LSP5 and LSP10 specs. 
See this PR in the LIP repository for reference: https://github.com/lukso-network/LIPs/pull/173
> refactor!: replace tuple value for LSP5/10 from `bytes8` -> `uint128`

- package.json
Without this export, we get that error when importing:
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './artifacts/LSP0ERC725Account.json' is not defined by "exports" in /myPath.../service-multichain-universalprofiles-contracts/node_modules/@lukso/lsp-smart-contracts/package.json.
```
> fix: export artifacts

- README.md
- constants.ts
Add the Typescript type alongside each values defined inside `constants.ts`.
Co-authored-by: Dominik Zborowski <dominik.zborowski@gmail.com>
> build: add Types to constant values

- contracts/LSP6KeyManager/LSP6Modules/LSP6ExecuteModule.sol
in the Key Manager, remove the internal function that extract the permission depending on the operation type.
Simply inline the first check for contract creation and simplify the logic for checking for the permission `CALL` or `STATICCALL`
> refactor: remove internal functions and add first check for contract creation permission

- tests/LSP6KeyManager/tests/PermissionCall.test.ts
- tests/LSP6KeyManager/tests/PermissionTransferValue.test.ts
> test: add more tests for LYX transfer with or without calldata

- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
This PR changes how the `LSP1UniversalReceiverDelegateUP` notifies the Universal Profile.
Instead of using `setData(...)` through the owner of the Universal Profile, it calls the Universal Profile directly.
> refactor: LSP1 calls the Universal Profile directly

- contracts/LSP6KeyManager/LSP6Modules/LSP6ExecuteModule.sol
- contracts/LSP6KeyManager/LSP6Utils.sol
- tests/LSP6KeyManager/tests/PermissionDeploy.test.ts
- ⛔️ Require `SUPER_TRANSFERVALUE` permission for deploying contracts with value
> fix!: require `SUPER_TRANSFERVALUE` permission for deploying contracts with value 

- contracts/LSP0ERC725Account/LSP0ERC725AccountInit.sol
- contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
- contracts/LSP6KeyManager/LSP6Utils.sol
- Rename some function parameters starting with underscore `_` as spotted by Slither.
- rename LSP6Utils library function `generatePermissionsKeysForController` to --> `generatePermissionsKeysForNewController` for better readability + add Natspec comment above function.
> chore: rename function parameters to mixedCase

- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/LSP1UniversalReceiverDelegateVault.sol
Slither report the following when running against `LSP1UniversalReceiverDelegateUP`
although this seems to be a false positive (as we are here dealing with `memory` variables, not `storage` ❌ ), refactor the code to allocate some memory for the array of `dataKeys[]` and `dataValues[]` first before to jump in the `if` checks.
This PR fixes the issue and remove the error reported by Slither.
> refactor: initialize memory vars before `if` checks in LSP1

- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP6KeyManager/LSP6Errors.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- package-lock.json
- package.json
- tests/LSP6KeyManager/tests/BatchExecute.test.ts
- tests/LSP6KeyManager/tests/PermissionSetData.test.ts
- tests/LSP9Vault/LSP9Vault.behaviour.ts
- tests/UniversalProfile.behaviour.ts
- Marking setData functions in LSP0 and LSP9 as payable
- Disallowing sending value to setData of LSP9
- Disallowing sending value to setData of LSP0 while having KM as owner. (In the KeyManager)
- Add needed tests
> feat!: Mark setData functions as payable

- contracts/LSP6KeyManager/LSP6Errors.sol
- contracts/LSP6KeyManager/LSP6Modules/LSP6ExecuteModule.sol
- tests/LSP20CallVerification/LSP6KeyManager/tests/BatchExecute.test.ts
- tests/LSP20CallVerification/LSP6KeyManager/tests/Reentrancy/SingleExecuteRelayCallToSingleExecute.test.ts
- tests/LSP20CallVerification/LSP6KeyManager/tests/Reentrancy/SingleExecuteToSingleExecute.test.ts
- tests/LSP20CallVerification/LSP6KeyManager/tests/Security.test.ts
- tests/LSP6KeyManager/tests/Security.test.ts
- Disallowing calling lsp20 functions by erc725x execute in the KM.
- Add relevant tests
- Resolve failing tests from previous PR
> fix: disallow calling LSP20 function on LSP6 through execute

- CHANGELOG.md
- package-lock.json
- package.json
- bump version in `package.json` and `package-lock.json`: `0.8.1` -> `0.9.0`
- add details of v0.9.0 release in release `CHANGELOG.md`
> chore: prepare-release-0.9.0

- .github/workflows/benchmark.yml
- .github/workflows/coverage.yml
Remove unecessary CI running when making releases. Including:
- merging `develop` -> `main`
- making PRs to `develop` that aim to bump the version in package.json + update the release CHANGELOG
> ci: do not run code coverage + gas benchmark CI on releases

- contracts/LSP14Ownable2Step/LSP14Ownable2Step.sol
- tests/LSP14Ownable2Step/LSP14Ownable2Step.behaviour.ts
- tests/LSP20CallVerification/LSP14CombinedWithLSP20.behaviour.ts
- Change `renounceOwnership(..)` delay to 200
- Change tests to the new delay
- Refactor few tests to beforeEach block instead of duplicated code
> refactor: change `renounceOwnership(..)` delay to 200

- CHANGELOG.md
- package-lock.json
- package.json
> This is to fix the artifacts import from 0.8.1, shipped in 0.9.0, but 0.9.0 includes too many breaking changes.
Fix package.json version and changelog to be able to manually publish the npm.
> chore: prepare patch release 0.8.2

- contracts/LSP0ERC725Account/ILSP0ERC725Account.sol
- contracts/LSP0ERC725Account/LSP0ERC725Account.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP6KeyManager/ILSP6KeyManager.sol
- contracts/LSP6KeyManager/LSP6Modules/LSP6SetDataModule.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/ILSP8CompatibleERC721.sol
- contracts/LSP9Vault/ILSP9Vault.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- Remove inheritance list in interfaces to avoid C3 Linearization issue when `Core` contract inherit abstract contracts that inherit the same interface.
- Move `ValueReceived` event inside `ILSP0` interface.
- Make `LSP0ERC725AccountCore` inherit from the `ILSP0` interface.
Cleanup comments + add comment above `VerifiedCall` event in LSP6.
> refactor: move `ValueReceived` event in LSP0 + LSP9 interfaces + delete interface inheritance for LSP0/9

- .github/workflows/foundry-tests.yml
Have foundry tests triggered in PR also when the PR is edited, not only when it is opened. To see gas changes when refactoring code while the PR is open.
Done by removing the `types` field in the github workflow syntax.
> ci: trigger foundry tests not only when PR is opened

- constants.ts
- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP20CallVerification/LSP20Constants.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/Mocks/ERC165Interfaces.sol
- tests/LSP6KeyManager/LSP6KeyManager.behaviour.ts
- tests/Mocks/ERC165Interfaces.test.ts
- tests/UniversalProfile.behaviour.ts
This PR introduces 2 new interface ids for LSP20.
Two new **interfaceIds**:
- The first one SHOULD be supported by the the LSP20 Verifier Contract, the contract that should verify if a call is valid. That interfaceId is constructed by using XOR of the selectors of the following function: `lsp20VerifyCall(address,uint256,bytes)` and `lsp20VerifyCallResult(bytes32,bytes)`
- The second one should be supported by the contract that implements LSP20CallVerification in its functions. And it is constructed by taking the first 4 bytes of "LSP20CallVerification" hash (`bytes4(keccack256("LSP20CallVerification"))`).
Fixes #????
> refactor: [TRST-M-6] Add LSP20 interfaceId to LSP0 & LSP6

- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/Mocks/Reentrancy/ThreeReentrancy.sol
- tests/LSP20CallVerification/LSP6/Interactions/Security.test.ts
- tests/Reentrancy/LSP6/LSP6Reentrancy.test.ts
The bug did not enable an attacker to execute an unauthorized action, but rather it permitted the execution of an action that the attacker was authorized to perform in a reentrant call without requiring Reentrancy Permission. This was possible by chaining the call with previous execute calls that deactivated the reentrancy guard.
The problem was fixed by making the function always tell if the call is a normal call or a reentrant call. If a reentrant call is detected, the function will not turn off the reentrancy guard/require a post-execution.
> fix: [TRST-H-1] Disallow turning reentrancy bool to false in reentrantCalls

- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/UniversalProfile.behaviour.ts
- Avoid reverts and return `FAILVALUE` when the signature is invalid in LSP0 and LSP6
> chore: [TRST-R-5] return `FAILVALUE` when the signature is invalid

- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721InitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Enumerable.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8EnumerableInitAbstract.sol
Mark state variables in LSP7 and LSP8 Core contracts as `private` instead of `internal`.
This aims to prevent some potential issues in implementation contracts via inheritance, to update these state variables by accident.
This can prevent issues such as:
- updating the total number of existing tokens (if no tokens have been minted or burnt)
- other way around, like minting and adding to the `_balances` mapping directly in LSP7 without updating the `_existingTokens` state variable.
See this tweet for more details: https://twitter.com/zarfsec/status/1605211608464216064
> refactor: mark `mapping` and state variables as `private` in LSP7/8 Core contracts

- contracts/LSP10ReceivedVaults/LSP10Utils.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/LSP1UniversalReceiverDelegateVault.sol
- contracts/LSP5ReceivedAssets/LSP5Utils.sol
Since PR #527 from @b00ste and this line change in the code:
https://github.com/lukso-network/lsp-smart-contracts/blob/2f984a954db0d673c83e78beb8989fc3a1d33cdd/contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol#L127
It is guaranteed that the `mapValue` will always be at least 20 bytes long.
This make the use of the `BytesLib.slice(...)` library unecessary inside the `LSP5Utils` and `LSP10Utils` libraries.
Remove the use of the `.slice` function and the function `extractIndexFromMap` in favour of simply converting explicitly to extract the 16 right most bytes in the map value.
This save around:
- around 150 to 220 gas at runtime for token transfers.
- around 27,288 gas of deployment cost for deploying a LSP1Delegate contract.
> perf: replace function `extractIndexFromMap(...)` and `BytesLib.slice` with explicit conversion

- package.json
Fix a typo in `"exports"` fields of the `package.json`.
The file name for the constants should be marked as plural `constants.js` :white_check_mark:, not singular `constant.js` :x:
This lead to some errors and not being able able to import the constant in certain development environnements like React Native.
> fix: typo in filename of exported `constant.js`

- contracts/LSP6KeyManager/LSP6Modules/LSP6SetDataModule.sol
Reduce gas cost of setting data keys related to:
- LSP6 permissions for controllers (`AddressPermissions:Permissions:<address>`) or controllers list (`AddressPermissions[]`)
- LSP1 Delegates
- LSP17 Extensions
This is done by avoiding multiple storage read via `getData(...)` if the controller making the request already has both permissions required.
Based on idea suggestion from @YamenMerhi in the LIP repo.
https://github.com/lukso-network/LIPs/issues/110#issuecomment-1445220995
> using the Gas Benchmark
> perf: save gas by not reading `target` storage when controller has both permissions already

- contracts/LSP7DigitalAsset/extensions/LSP7CappedSupply.sol
- contracts/LSP7DigitalAsset/extensions/LSP7CappedSupplyInitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CappedSupply.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CappedSupplyInitAbstract.sol
In `LSP7CappedSupply` and `LSP8CappedSupply`, mark the variable `_tokenSupplyCap` as `immutable` as this variable is set only in the constructor. This will change the data location from storage to code and optimise the internal `_mint` function since the getter will not read from storage anymore (expensive) but from the contract bytecode.
In `LSP7CappedSupply`, `LSP7CappedSupplyInit`, LSP8CappedSupply` and `LSP8CappedSupplyInit`, change the visibility of `_tokenSupplyCap` from `internal` to `private`.
This makes the code more robust and secure:
- for inheritance on `LSP7CappedSupply` and `LSP8CappedSupply` (prevent overriding this state variable in future inheriting contracts). This is similar to what was introduced in #584 
- in the 4 contracts, enforces the use of the getter function …
> refactor: mark `_tokenSupplyCap` as `private` + `immutable` for optimisation

- contracts/LSP7DigitalAsset/extensions/LSP7Burnable.sol
- contracts/LSP7DigitalAsset/extensions/LSP7BurnableInitAbstract.sol
- contracts/Mocks/Tokens/LSP7InitTester.sol
Add Init version of `LSP7Burnable` extension.
Change the inheritance in `LSP7Burnable` to inherit from the standard version of LSP7 and prevent state variable `_isNonDivisible` to be uninitialized. See error reported by Slither below:
> fix: initialize state var in inheritance of `LSP7Burnable` + add init version of this extension

- contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.sol
- contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20InitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721InitAbstract.sol
**apply to:** `LSP7CompatibleERC20`, `LSP7CompatibleERC20Init`, `LSP8CompatibleERC721` and `LSP8CompatibleERC721`.
In these contracts, inside the internal `_mint`, `_burn` and `_transfer` functions, the `Transfer` event is emitted after the call to the `super` function (`super._mint`, `super._burn` and `super._transfer` functions).
Since the parent function performs an external call to notify the token sender and/or recipient, this can potentially lead to reentrancy scenarios.
In the context of reentrancy, the second `Transfer` event would appear first in the logs, and the initial `Transfer` event would appear second, leading to an incorrect order of event emission according to the interaction.
Refactor to emit the `Transfer` event first in the compatible functions before any external …
> fix: emit `Transfer` LSP7/8 compatible events before external calls

- hardhat.config.ts
- tests/LSP6KeyManager/Relay/ExecuteRelayCall.test.ts
- Fix failing validity timestamp
Old behavior was manipulating the timestamp with increasing time on each test
New behavior tests each case against the current timestamp
> test: fix failing validity timestamp

- .github/workflows/deploy-verify.yml
- DEPLOYMENT.md
- hardhat.config.ts
- scripts/ci/README.md
- scripts/ci/check-deployer-balance.ts
- scripts/ci/deploy-verify.sh
- Update CI to deploy and verify smart contracts on the new LUKSO testnet instead of L16.
- **:warning: Warning: deprecate the L14 and L16 test networks by removing them from the hardhat config.**
> ci: replace deployment + verification of contracts from L16 to LUKSO Testnet

- contracts/LSP0ERC725Account/LSP0ERC725Account.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountInit.sol
- contracts/LSP0ERC725Account/LSP0ERC725AccountInitAbstract.sol
- contracts/UniversalProfile.sol
- contracts/UniversalProfileInit.sol
- contracts/UniversalProfileInitAbstract.sol
In LSP0 and UP contracts, rename the parameter from `newOwner` to `initialOwner` for the `constructor`, public `initialize(address)` and ``_initialize(...)` function.
Improve the Natspec tags for these functions for the tags `@dev` and `@notice`.
> docs: rename deploy params to `initialOwner` and `contractOwner` for UP and LSP0 contracts

- .github/PULL_REQUEST_TEMPLATE.md
Simplify the comments in the PR template, to have all the headings listed together in the same Markdown comment.
> chore: simplify comments for PR template

- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
Slither reports the following variable shadowing in `LSP0ERC725AccountCore.sol`.
Despite that the `_pendingOwner` variable is defined as `private` inside `LSP14`, rename the variable so that the parameter name of the function `transferOwnership` does not clash the name with the state variable `_pendingOwner`.
> fix: variable shadowing with `transferOwnership(_pendingOwner)` and `_pendingOwner` state variable

- contracts/LSP2ERC725YJSONSchema/LSP2Utils.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP6KeyManager/LSP6Modules/LSP6ExecuteModule.sol
- contracts/LSP6KeyManager/LSP6Modules/LSP6SetDataModule.sol
- contracts/LSP6KeyManager/LSP6Utils.sol
Slither reports uninitialized local variables in `LSP2Utils` and the `LSP6KeyManager`.
Initialize these variables to their default values `0` and `false` for the boolean `isSettingERC725YDataKeys`.
This improves the readability a bit while not adding to much gas in the deployment cost of the Key Manager (+12 gas for deploying a `LSP6KeyManager`).
> refactor: initialize local variables to `0` (iterators) and `false` for booleans

- contracts/LSP17ContractExtension/LSP17Extension.sol
- contracts/LSP6KeyManager/LSP6Modules/LSP6ExecuteModule.sol
> Note: also removed in this PR a `// solhint-disable` comment that was unecessary
Slither reports a literal with too many digits in `LSP6ExecuteModule`. The literal is related to the offset of `data` parameter when verifying `ERC725X.execute(...)` payloads in the Key Manager.
Refactor and use the offset as a plain number `128` to describe the index in the calldata where the `data` parameter is located + describe this line with code comments.
> chore: improve readability using number instead of long hex string

- .github/workflows/benchmark.yml
- .github/workflows/build-lint-test.yml
- .github/workflows/coverage.yml
- .github/workflows/deploy-verify.yml
- .github/workflows/foundry-tests.yml
- .github/workflows/publish-npm-artifact.yml
Replace CI commands from `npm run build` to `npx hardhat compile`.
This is to fix the error that occurs at random when generating the contracts artifacts + generating the docs at the same time.
https://github.com/lukso-network/lsp-smart-contracts/actions/runs/5335783332/jobs/9685846728
> ci: use `hardhat compile` command to generate build

- CHANGELOG.md
- hardhat.config.ts
Upgrade default solc compiler version from 0.8.15 to 0.8.17
> build: upgrade solc compiler version to 0.8.17

- .github/workflows/build-lint-test.yml
- .gitignore
- package.json
- tests/importRequire.sh
🐛 Bug: The package.json had the require and import sections
Add package.json into the export sections, which was missing.
> fix: Repair problem in package.json where require/import was swapped. Add in export of package.json

- CHANGELOG.md
- package-lock.json
- package.json
This PR prepare for a patch release of the smart contracts package that include a bug fix for importing values from the `constants.es.js` or `constants.cjs.js`. See #633 for details.
- Bump version in `package.json` from `0.10.2` to `0.10.3`.
- Add details of release and commits references in `CHANGELOG.md`.
> chore: prepare release 0.10.3

- CHANGELOG.md
- package-lock.json
- package.json
- Bump version in `package.json` from `0.10.3` to `0.11.0-rc.0`
- Add details in release `CHANGELOG.md`
> chore: prepare release 0.11.0-rc.0

- .github/workflows/build-lint-test.yml
- CHANGELOG.md
- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP20CallVerification/LSP20CallVerification.sol
- contracts/LSP23MultiChainDeployment/IOwnerControlledContractDeployer.sol
- contracts/LSP23MultiChainDeployment/IPostDeploymentModule.sol
- contracts/LSP23MultiChainDeployment/LSP23Errors.sol
- contracts/LSP23MultiChainDeployment/OwnerControlledContractDeployer.sol
- contracts/LSP23MultiChainDeployment/modules/UniversalProfileInitPostDeploymentModule.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP6KeyManager/LSP6Modules/LSP6ExecuteModule.sol
- contracts/LSP6KeyManager/LSP6Modules/LSP6SetDataModule.sol
- contracts/LSP7DigitalAsset/extensions/LSP7Burnable.sol
- contracts/LSP7DigitalAsset/extensions/LSP7BurnableInitAbstract.sol
- contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20Mintable.sol
- contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20MintableInitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Burnable.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721InitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8CompatibleERC721Mintable.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8CompatibleERC721MintableInitAbstract.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- package-lock.json
- package.json
- tests/LSP23MultiChainDeployment/LSP23MultiChainDeployment.behaviour.ts
- tests/LSP23MultiChainDeployment/LSP23MultiChainDeployment.test.ts
- tests/LSP23MultiChainDeployment/helpers.ts
- change visibility of `_reentrancyStatus` state variable from `private` to `internal` ([#651](https://github.com/lukso-network/lsp-smart-contracts/pull/651))
- create LSP23MultiChainDeployment ([#649](https://github.com/lukso-network/lsp-smart-contracts/issues/649)) ([01fd820](https://github.com/lukso-network/lsp-smart-contracts/commit/01fd82038811ba65798f3ff8fe8273fd191dcb38)), closes [#650](https://github.com/lukso-network/lsp-smart-contracts/issues/650)
- change visibility of `_reentrancyStatus` state variable from `private` to `internal` ([#651](https://github.com/lukso-network/lsp-smart-contracts/pull/651))
> chore(release): 0.11.0-rc.0

- CHANGELOG.md
- package-lock.json
- package.json
- bump version in `package.json` from `0.11.0-rc.0` to `0.11.0-rc.1`
- add details to release `CHANGELOG.md`
> chore(release): 0.11.0-rc.1

- .solcover.js
Remove the `Create2Factory` contract from the contracts used to generate the code coverage stats. This Factory is not used anymore and is legacy, giving a wrong indication of the actual code coverage.
> chore: remove `Create2Factory` from code coverage

- docs/contracts/ERC725/ERC725.md
Add auto-generated docs for `ERC725` smart contracts under a folder `docs/ERC725/ERC725.md`.
- update filepath in dodoc config + adjust helper scripts
> docs: improve ERC725 Natspec comments + add auto-generated docs

- contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
- contracts/LSP14Ownable2Step/LSP14Errors.sol
- contracts/LSP14Ownable2Step/LSP14Ownable2Step.sol
- docs/contracts/LSP14Ownable2Step/LSP14Ownable2Step.md
> 🕐 **This PR is in draft and awaiting an update in the `@b00ste/hardhat-dodoc` package.** Do not review yet until this notice is gone and the PR in in "ready for review" mode.
This PR updates the Natspec of the LSP14 contracts.
> docs: update LSP14 Natspec

- contracts/LSP6KeyManager/LSP6Utils.sol
- tests/foundry/LSP6KeyManager/LSP6RestrictedController.t.sol
- tests/foundry/LSP6KeyManager/LSP6Utils.t.sol
The function `combinePermissions` adds permission together into a final combined value.
If the same permission is added twice, then this will result in a new and different permission.
For example adding `_PERMISSION_STATICCALL` twice results in `_PERMISSION_SUPER_DELEGATECALL`.
- Fix the bug by using bitwise `OR` / `|` inside the function.
- Add a set of Foundry tests to test the function `combinePermissions` + re-use the Foundry test used as a PoC in the issue **sligthly modified to test for revert**.
> fix: (C4 #13) use bitwise `OR` / `|` to avoid combining two permissions twice

- constants.ts
- contracts/LSP0ERC725Account/LSP0Constants.sol
- contracts/Mocks/ERC165Interfaces.sol
Add LSP20 in calculation of LSP0 interface.
The interface ID of LSP0 changed from `0x3e89ad98` to -> `0x24871b3d`
> refactor!: add LSP20 in calculation of LSP0 interface ID

- contracts/LSP6KeyManager/ILSP6KeyManager.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- tests/LSP20CallVerification/LSP6/Interactions/PermissionCall.test.ts
- tests/LSP6KeyManager/Relay/ExecuteRelayCall.test.ts
Change event name from `VerifiedCalled` to `PermissionsVerified` in LSP6 specs.
> refactor!: change event name from VerifiedCalled to PermissionsVerified in LSP6

- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8BurnableInitAbstract.sol
- contracts/Mocks/Tokens/LSP8BurnableInitTester.sol
- contracts/Mocks/Tokens/LSP8BurnableTester.sol
- contracts/Mocks/Tokens/LSP8InitTester.sol
- tests/LSP8IdentifiableDigitalAsset/proxy/LSP8BurnableInit.test.ts
- tests/LSP8IdentifiableDigitalAsset/standard/LSP8Burnable.test.ts
The `LSP8Burnable` contract inherits from `LSP8IdentifiableDigitalAssetCore`:
```solidity
abstract contract LSP8Burnable is LSP8IdentifiableDigitalAssetCore {
```
However, LSP8 extensions are supposed to inherit `LSP8IdentifiableDigitalAsset` instead. This can be inferred by looking at `LSP8CappedSupply.sol`
```solidity
abstract contract LSP8CappedSupply is LSP8IdentifiableDigitalAsset {
```
Additionally, the `LSP8BurnableInitAbstract.sol` file is missing in the repository.
As `LSP8Burnable` does not inherit `LSP8IdentifiableDigitalAsset`, a developer who implements his LSP8 token using `LSP8Burnable` will face the following issues:
- All functionality from `LSP4DigitalAssetMetadata` will be unavailable.
= As `LSP8Burnable` does not contain a `supportsInterface()` function, it will be …
> fix: (C4 #120) inheritance of `LSP8Burnable` + add tests to check LSP4 Metadata is set correctly on deployment + initialization

- .github/workflows/solc_version.yml
Add the in the matrix of the `solc_version.yaml` new versions of Solidity compiler `0.8.18` to `0.8.21` to ensure the `@lukso/lsp-smart-contracts` compile with the latest Solidity versions.
> ci: add new solc versions in CI

- contracts/LSP7DigitalAsset/ILSP7DigitalAsset.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAsset.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP7DigitalAsset/LSP7Errors.sol
- docs/contracts/LSP7DigitalAsset/LSP7DigitalAsset.md
Improve Natspec comments for `LSP7DigitalAsset` and add auto-generated docs.
> docs: improve LSP7 Natspec comments + add auto-generated docs

- contracts/LSP23LinkedContractsDeployment/ILSP23LinkedContractsFactory.sol
- contracts/LSP23LinkedContractsDeployment/LSP23LinkedContractsFactory.sol
- contracts/LSP23LinkedContractsDeployment/modules/UniversalProfileInitPostDeploymentModule.sol
- contracts/LSP23LinkedContractsDeployment/modules/UniversalProfilePostDeploymentModule.sol
- docs/contracts/LSP23LinkedContractsDeployment/LSP23LinkedContractsFactory.md
- dodoc/config.ts
- hardhat.config.ts
- tests/LSP23LinkedContractsDeployment/LSP23LinkedContractsDeployment.test.ts
- tests/LSP23LinkedContractsDeployment/helpers.ts
Rename `LinkedContractsFactory` to `LSP23LinkedContractsFactory`
> refactor: rename to LSP23LinkedContractsFactory

- contracts/Mocks/Tokens/TokenReceiverWithLSP1.sol
- contracts/Mocks/Tokens/TokenReceiverWithLSP1WithERC721Received.sol
- contracts/Mocks/Tokens/TokenReceiverWithLSP1WithERC721ReceivedInvalid.sol
- contracts/Mocks/Tokens/TokenReceiverWithLSP1WithERC721ReceivedRevert.sol
- contracts/Mocks/Tokens/TokenReceiverWithoutLSP1WithERC721Received.sol
- contracts/Mocks/Tokens/TokenReceiverWithoutLSP1WithERC721ReceivedInvalid.sol
- contracts/Mocks/Tokens/TokenReceiverWithoutLSP1WithERC721ReceivedRevert.sol
- tests/LSP20CallVerification/LSP6/LSP20WithLSP6.test.ts
- tests/LSP20CallVerification/LSP6/SetPermissions/SetAllowedCalls.test.ts
- tests/LSP6KeyManager/Relay/MultiChannelNonce.test.ts
- tests/LSP6KeyManager/SetPermissions/SetAllowedCalls.test.ts
- tests/LSP6KeyManager/internals/AllowedCalls.internal.ts
- tests/LSP7DigitalAsset/LSP7CompatibleERC20.behaviour.ts
- tests/LSP7DigitalAsset/LSP7DigitalAsset.behaviour.ts
- tests/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.behaviour.ts
- tests/Reentrancy/LSP20/LSP20WithLSP6Reentrancy.test.ts
- Resolve all the tests related to Allowed Calls in the Key Manager that are marked as `.skip` (no more skipped tests in the whole test suite).
- Resolve the TODOs included in the Key Manager tests + in LSP7 for the `UniversalReceiver` event.
- Replace the emitted event `UniversalReceiverCalled` by the native `UniversalReceiver` event from LSP1 for mock contracts that inherit from LSP1.
> test: resolve `.skip` and `TODOs` tests in LSP6 + LSP7

- contracts/LSP6KeyManager/LSP6Modules/LSP6SetDataModule.sol
- tests/LSP6KeyManager/SetData/AllowedERC725YDataKeys.test.ts
- tests/LSP6KeyManager/internals/AllowedERC725YDataKeys.internal.ts
- tests/foundry/LSP6KeyManager/LSP6SetDataTest.t.sol
There is an insufficient length check when validating the allowed data keys that can be set by a caller. In particular, if a decoded length in the compact bytes array happens to be 0, the caller will be validated against any data key.
Although a decoded length is not possible when setting allowed data keys via the `LSP6SetDataModule` contract, there is no guarantee that data values before ownership transfer to an LSP6 contract are valid. This allows a scamming opportunity as malicious actors who set-up an ERC725 contract for another can create a backdoor that cannot be easily seen as the allowed data keys will simply have an extra `0x0000`.
When verifying allowed data keys that a caller can set, a length check is done on the first 2 bytes of a compact bytes array to ensure that the length …
> fix: (C4 #97) add check for `length == 0` to prevent `mask` to allow any data key

- contracts/LSP6KeyManager/LSP6Errors.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP6KeyManager/LSP6Modules/LSP6ExecuteModule.sol
- contracts/Mocks/KeyManager/KeyManagerInternalsTester.sol
- contracts/Mocks/TargetContract.sol
- docs/contracts/LSP6KeyManager/LSP6KeyManager.md
- tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP.behaviour.ts
- tests/LSP20CallVerification/LSP6/Interactions/PermissionCall.test.ts
- tests/LSP6KeyManager/Interactions/PermissionCall.test.ts
- tests/LSP6KeyManager/LSP6KeyManager.test.ts
- tests/LSP6KeyManager/Relay/ExecuteRelayCall.test.ts
- tests/LSP6KeyManager/internals/AllowedCalls.internal.ts
- tests/LSP6KeyManager/internals/Execute.internal.ts
Replace calldata slices by `abi.decode` in the Key Manager for extracting the ERC725X execute parameters.
This reduce the deployment cost + runtime cost as follow (except for the main controller).
- [] Wrote & Generated Documentation (readme/natspec/dodoc)
> perf: replace calldata slices by `abi.decode` to extract `ERC725X.execute` params

- contracts/LSP6KeyManager/LSP6Errors.sol
- contracts/LSP6KeyManager/LSP6Modules/LSP6SetDataModule.sol
- docs/contracts/LSP6KeyManager/LSP6KeyManager.md
- tests/LSP20CallVerification/LSP6/Admin/PermissionChangeAddExtensions.test.ts
- tests/LSP20CallVerification/LSP6/SetPermissions/PermissionChangeAddController.test.ts
- tests/LSP6KeyManager/Admin/PermissionChangeAddExtensions.test.ts
- tests/LSP6KeyManager/LSP6ControlledToken.test.ts
- tests/LSP6KeyManager/SetPermissions/PermissionChangeAddController.test.ts
Add input validations for the data values of specific data keys.
> refactor: add input validations when setting data in `LSP6SetDataModule`

- docs/_interface_ids_table.mdx
- docs/contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecovery.md
- docs/contracts/LSP17ContractExtension/LSP17Extendable.md
- docs/contracts/LSP17ContractExtension/LSP17Extension.md
- docs/contracts/LSP20CallVerification/LSP20CallVerification.md
- docs/contracts/LSP23LinkedContractsDeployment/IPostDeploymentModule.md
- docs/contracts/LSP23LinkedContractsDeployment/LSP23LinkedContractsFactory.md
- docs/contracts/LSP25ExecuteRelayCall/LSP25MultiChannelNonce.md
- docs/contracts/LSP4DigitalAssetMetadata/LSP4Compatibility.md
- docs/contracts/LSP6KeyManager/LSP6KeyManager.md
- docs/contracts/LSP7DigitalAsset/LSP7DigitalAsset.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7Burnable.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CappedSupply.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20Mintable.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7Mintable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.md
- docs/contracts/LSP9Vault/LSP9Vault.md
- docs/contracts/UniversalProfile.md
- dodoc/config.ts
- Add updated Markdown docs from Natspec comments.
- Add table of generated ERC165 interface IDs in Markdown
> docs: add updated Markdown generated docs from Natspec

- contracts/LSP1UniversalReceiver/LSP1Utils.sol
- contracts/LSP2ERC725YJSONSchema/LSP2Utils.sol
- docs/libraries/LSP1UniversalReceiver/LSP1Utils.md
Remove function `getTransferDetails` from `LSP1Utils.sol`, as this function is not used anymore in the LSP1 Delegate implementation for UP and Vault.
Also removed the function from the auto-generated docs.
> chore: :coffin: remove unused function `getTransferDetails` from `LSP1Utils.sol`

- docs/contracts/ERC725/ERC725.md
- docs/contracts/LSP0ERC725Account/LSP0ERC725Account.md
- docs/contracts/LSP4DigitalAssetMetadata/LSP4Compatibility.md
- docs/contracts/LSP4DigitalAssetMetadata/LSP4DigitalAssetMetadata.md
- docs/contracts/LSP6KeyManager/LSP6KeyManager.md
- docs/contracts/LSP7DigitalAsset/LSP7DigitalAsset.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7Burnable.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CappedSupply.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20Mintable.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7Mintable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Burnable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CappedSupply.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Enumerable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/presets/LSP8CompatibleERC721Mintable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/presets/LSP8Mintable.md
- docs/contracts/LSP9Vault/LSP9Vault.md
- docs/contracts/UniversalProfile.md
- docs/libraries/LSP2ERC725YJSONSchema/LSP2Utils.md
- package-lock.json
- package.json
Upgrade `@erc725/smart-contracts` package from `5.1.0` to `5.2.0` to get the latest up to date Natspec comments.
Update all the auto generated docs for the contracts that inherit the methods from ERC725X and ERC725Y, so that it gets the new Natspec comments.
> build: upgrade `@erc725/smart-contracts` to 5.2.0 + generate new ABI docs

- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- contracts/Mocks/UniversalReceivers/UniversalReceiverDelegateTokenReentrant.sol
- tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP.behaviour.ts
- tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault.behaviour.ts
- tests/LSP7DigitalAsset/LSP7DigitalAsset.behaviour.ts
- tests/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.behaviour.ts
Change `abi.encodePacked` to `abi.encode` when notifying LSP1 from LSP7 or LSP8
> refactor: Change `abi.encodePacked` => `abi.encode` in LSP7 & LSP8

- CHANGELOG.md
- package.json
- Include LSP20 in interfaceId calculation ([#668](https://github.com/lukso-network/lsp-smart-contracts/pull/668)), from: `0x3e89ad98` to `0x24871b3d`
- Return instead of revert when the `LSP1UniversalReceiverDelegateUP` is not able to register LSP5-LSP10 data keys. ([#672](https://github.com/lukso-network/lsp-smart-contracts/pull/672))
- Change event name in LSP6 from `VerifiedCall` to `PermissionsVerified`. ([#673](https://github.com/lukso-network/lsp-smart-contracts/pull/673))
- Rename LSP23 to `LSP23LinkedContractsFactory`. ([#675](https://github.com/lukso-network/lsp-smart-contracts/pull/675))
- Change LSP6 interfaceId from `0x38bb3cdb` to `0x66918867`. ([#696](https://github.com/lukso-network/lsp-smart-contracts/pull/696))
- Change LSP7 interfaceId from `0xda1f85e4` to `0x05519512`. …
> chore(release): v0.11.0

- CHANGELOG.md
- package.json
- Include LSP20 in interfaceId calculation ([#668](https://github.com/lukso-network/lsp-smart-contracts/pull/668)), from: `0x3e89ad98` to `0x24871b3d`
- Return instead of revert when the `LSP1UniversalReceiverDelegateUP` is not able to register LSP5-LSP10 data keys. ([#672](https://github.com/lukso-network/lsp-smart-contracts/pull/672))
- Change event name in LSP6 from `VerifiedCall` to `PermissionsVerified`. ([#673](https://github.com/lukso-network/lsp-smart-contracts/pull/673))
- Rename LSP23 to `LSP23LinkedContractsFactory`. ([#675](https://github.com/lukso-network/lsp-smart-contracts/pull/675))
- Change LSP6 interfaceId from `0x38bb3cdb` to `0x66918867`. ([#696](https://github.com/lukso-network/lsp-smart-contracts/pull/696))
- Change LSP7 interfaceId from `0xda1f85e4` to `0x05519512`. …
> chore(release): v0.11.1

- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
The comments in LSP0 > universalReceiver was mentioning `
{_LSP1_UNIVERSAL_RECEIVER_DELEGATE_KEY + <bytes32 typeId>}` instead of `
{_LSP1_UNIVERSAL_RECEIVER_DELEGATE_PREFIX + <bytes32 typeId>}`
> chore: fix comment typo in LSP0

- tests/LSP17ContractExtension/LSP17ExtendableTokens.behaviour.ts
- tests/LSP23LinkedContractsDeployment/LSP23LinkedContractsDeployment.test.ts
There were some ESLint warnings introduced in #697 that got missed + one ES Lint warning in the LSP23 tests.
> chore: fix ESLint warnings in LSP17 and LSP23 tests

- README.md
- constants.ts
Add Typescript types of the JSON structure for the metadata of LSP3Profile and LSP4DigitalAsset.
These types are currently defined in the lsp-factory, but have a better place in the lsp-smart-contracts repository, to be imported from the constants.
https://github.com/lukso-network/tools-lsp-factory/blob/develop/src/lib/interfaces/lsp3-profile.ts
https://github.com/lukso-network/tools-lsp-factory/blob/develop/src/lib/interfaces/lsp4-digital-asset.ts
https://github.com/lukso-network/tools-lsp-factory/blob/develop/src/lib/interfaces/metadata.ts
> build: add TS types for JSON Metadata of LSP3 and LSP4

- contracts/LSP6KeyManager/LSP6Modules/LSP6SetDataModule.sol
- contracts/LSP6KeyManager/LSP6Utils.sol
- docs/libraries/LSP6KeyManager/LSP6Utils.md
- tests/LSP6KeyManager/SetPermissions/PermissionChangeAddController.test.ts
- **Important Bug Fix**: fix the check against permissions `ADD_CONTROLLER` vs `EDIT_PERMISSIONS`. If the permission value stored under the controller we are setting the permissions for is not exactly 32 bytes long, consider it as _"no permissions set"_, and **require the permission `ADD_CONTROLLER`**.
- Add check in function `getPermissionsFor` to ensure that the raw `bytes` value of a permission fetched from the ERC725Y storage are **exactly 32 bytes long**. If they raw bytes value is not 32 bytes long, consider this as no permissions check.
This is to make it consistent with the input validation below in `LSP6SetDataModule`.
- Add info Natspec tag above this function and update auto generated docs.
- Add extra tests for the new bug fix mentioned above, depending on the caller's …
> fix: add check for permission value length in `_getPermissionToSetControllerPermissions` and in `LSP6Utils` function `getPermissionsFor`

- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP17ContractExtension/LSP17Extendable.sol
- contracts/LSP17ContractExtension/LSP17Extension.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAsset.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetInitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetInitAbstract.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- docs/contracts/LSP0ERC725Account/LSP0ERC725Account.md
- docs/contracts/LSP17ContractExtension/LSP17Extendable.md
- docs/contracts/LSP17ContractExtension/LSP17Extension.md
- docs/contracts/LSP7DigitalAsset/LSP7DigitalAsset.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7Burnable.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CappedSupply.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20Mintable.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7Mintable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Burnable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CappedSupply.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Enumerable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/presets/LSP8CompatibleERC721Mintable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/presets/LSP8Mintable.md
- docs/contracts/LSP9Vault/LSP9Vault.md
- docs/contracts/UniversalProfile.md
Add note in Natspec comment above `_fallbackLSP17Extendable` function about the fact that this function does not forward the `msg.value` to the extension contract + add basic code snippet to show how this can be done.
Related to Code4Rena QA nb 141, L-02
> docs: add LSP17 Natspec about `msg.value` not forwarded to extension

- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/Mocks/KeyManager/KeyManagerInternalsTester.sol
- docs/contracts/LSP6KeyManager/LSP6KeyManager.md
- tests/LSP6KeyManager/internals/Execute.internal.ts
In QA 15 from Code4Rena, it is suggested that the event emission was missing in the function `lsp20VerifyCall` when the caller was not the `target`
This is intended behaviour to allow permissions verification in a read-only manner, without toggling the reentrancy flag or emitting the event (such as in the case of EIP4337). Add Natspec comments to document this intended behaviour.
> docs: add Natspec comments to document read-only permissions verifications in `LSP6KeyManager` via `lsp20VerifyCall`

- contracts/LSP7DigitalAsset/LSP7DigitalAsset.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetInitAbstract.sol
- contracts/LSP7DigitalAsset/LSP7Errors.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8Errors.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetInitAbstract.sol
- docs/contracts/LSP7DigitalAsset/LSP7DigitalAsset.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7Burnable.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CappedSupply.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20Mintable.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7Mintable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Burnable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CappedSupply.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Enumerable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/presets/LSP8CompatibleERC721Mintable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/presets/LSP8Mintable.md
- tests/LSP17ContractExtension/LSP17ExtendableTokens.behaviour.ts
- tests/LSP7DigitalAsset/LSP7DigitalAsset.behaviour.ts
- tests/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.behaviour.ts
This PR introduces the following changes:
- New error in both LSP7 & LSP8 for not allowing sending native tokens to LSP7 & LSP8 contracts.
- Add `receive()` that reverts in LSP7 & LSP8
> fix: add `receive()` function in LSP7 & LSP8 to silent compiler warning

- contracts/LSP25ExecuteRelayCall/LSP25MultiChannelNonce.sol
- tests/LSP6KeyManager/Relay/ExecuteRelayCall.test.ts
Allow the validity timestamp in a relay call to start but never end
> feat: allow `endingTimestamp` to be 0

- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP7DigitalAsset/extensions/LSP7Burnable.sol
- contracts/LSP7DigitalAsset/extensions/LSP7BurnableInitAbstract.sol
- docs/contracts/LSP7DigitalAsset/LSP7DigitalAsset.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7Burnable.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CappedSupply.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20Mintable.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7Mintable.md
- tests/LSP7DigitalAsset/LSP7DigitalAsset.behaviour.ts
- Remove the logic to check for the operator allowance inside the internal `_burn` function in LSP7 + move this function in the public `burn(...)` function in the extension `LSP7Burnable`.
- Create internal function `_spendAllowance`.
- Add tests to ensure operators is removed from list when burning all its allowance.
- Add tests to check for event emitted `AuthorizedOperator` and `RevokedOperator` when burning as an operator.
- Update the custom error when operator try to burn using `address(0)` as `from` (matches with OpenZeppelin logic on ERC20 implementation)
- Add Natspec comments + update auto-generated docs.
> refactor: remove operator logic from internal `_burn` function in LSP7

- .github/workflows/benchmark.yml
- .gitignore
- hardhat.config.ts
- scripts/ci/gas_benchmark.ts
- scripts/ci/gas_benchmark_template.json
- tests/Benchmark.test.ts
Create new hardhat task `hardhat gas-benchmark` to generate a table with a gas diff, based on the pre-defined scenarios set in the test file `Benchmark.test.ts`.
Update the CI to generate the gas report by comparing the gas figures of the base _vs_ target branch.
> ci: update gas benchmark CI to display gas diffs as well as the figures

- contracts/LSP6KeyManager/LSP6Modules/LSP6SetDataModule.sol
- docs/contracts/LSP6KeyManager/LSP6KeyManager.md
- tests/LSP20CallVerification/LSP6/SetPermissions/SetAllowedCalls.test.ts
- tests/LSP20CallVerification/LSP6/SetPermissions/SetAllowedERC725YDataKeys.test.ts
- tests/LSP6KeyManager/SetPermissions/SetAllowedCalls.test.ts
- tests/LSP6KeyManager/SetPermissions/SetAllowedERC725YDataKeys.test.ts
This PR solves a small user bug.
When setting the Allowed Calls or Allowed ERC725Y Data Keys of a controller, currently the logic to check if the permission needed to set these values between `ADD_CONTROLLER` or `EDIT_PERMISSIONS` is to check against the value for the data key being set. This data key can be:
- `AddressPermissions:AllowedCalls:<controller>`
- `AddressPermissions:AllowedERC725YDataKeys:<controller>`
Update this logic to check now if the controller is actually a controller with some permission, by checking under the `AddressPermissions:Permissions:<controller>` instead.
> fix: update logic to check against controller permissions when setting its Allowed Calls or ERC725Y Data Keys

- .github/workflows/solc_version.yml
- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
- contracts/LSP14Ownable2Step/LSP14Ownable2Step.sol
- contracts/LSP17Extensions/Extension4337.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
- contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/LSP1UniversalReceiverDelegateVault.sol
- contracts/LSP23LinkedContractsFactory/LSP23LinkedContractsFactory.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP7DigitalAsset/presets/LSP7Mintable.sol
- contracts/LSP7DigitalAsset/presets/LSP7MintableInitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8Mintable.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8MintableInitAbstract.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- contracts/Mocks/FallbackExtensions/ERC165Extension.sol
- contracts/Mocks/UniversalReceivers/UniversalReceiverDelegateGasConsumer.sol
- contracts/Mocks/UniversalReceivers/UniversalReceiverDelegateRevert.sol
- contracts/Mocks/UniversalReceivers/UniversalReceiverDelegateVaultReentrantA.sol
- contracts/Mocks/UniversalReceivers/UniversalReceiverDelegateVaultReentrantB.sol
- scripts/ci/gas_benchmark.ts
Add the `override` keyword to allow compiling with older solc compiler versions before `0.8.8`.
Uncomment versions in `solc_versions.yaml` to test for compiling with older solc versions:
- `0.8.7`
- `0.8.6`
- `0.8.5`
Update the CI to also run when changes are merged in the develop branch.
> refactor: update contracts to allow compiling with solc versions `0.8.7`, `.6` and `.5`

- contracts/LSP20CallVerification/LSP20CallVerification.sol
- contracts/LSP6KeyManager/LSP6Errors.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/Mocks/KeyManager/KeyManagerInternalsTester.sol
- docs/contracts/LSP6KeyManager/LSP6KeyManager.md
- tests/LSP6KeyManager/Interactions/BatchExecute.test.ts
- tests/LSP6KeyManager/SetData/PermissionSetData.test.ts
- tests/LSP6KeyManager/internals/Execute.internal.ts
> feat: allow sending value when using `setData(..)` through the LSP6

- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
Reduce double check for `_exist` inside LSP8 Core internal `_mint` function.
> perf: remove double `_exist` check in LSP8Core

- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
Minor change to adjust the storage layout of the token contracts so that they look similar between LSP7 and LSP8.
> refactor: adjust LSP7 storage layout like LSP8

- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Enumerable.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8EnumerableInitAbstract.sol
- docs/contracts/LSP7DigitalAsset/LSP7DigitalAsset.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7Burnable.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CappedSupply.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20Mintable.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7Mintable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Burnable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CappedSupply.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Enumerable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/presets/LSP8CompatibleERC721Mintable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/presets/LSP8Mintable.md
Add internal function `_afterTokenTransfer` that can be overriden to run logic after tokens have been transferred + event `Transfer` has been emitted.
Update auto-generated docs.
> feat: add `_afterTokenTransfer` internal function in LSP7 + LSP8

- constants.ts
- contracts/LSP17Extensions/Extension4337.sol
- contracts/LSP20CallVerification/ILSP20CallVerifier.sol
- contracts/LSP20CallVerification/LSP20CallVerification.sol
- contracts/LSP20CallVerification/LSP20Constants.sol
- contracts/LSP6KeyManager/LSP6Constants.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/Mocks/ERC165Interfaces.sol
- contracts/Mocks/LSP20Owners/FirstCallReturnExpandedInvalidValue.sol
- contracts/Mocks/LSP20Owners/FirstCallReturnInvalidMagicValue.sol
- docs/_interface_ids_table.mdx
- docs/contracts/LSP6KeyManager/LSP6KeyManager.md
- tests/LSP20CallVerification/LSP6/Interactions/PermissionCall.test.ts
- tests/LSP20CallVerification/LSP6/Interactions/Security.test.ts
- tests/LSP6KeyManager/Interactions/PermissionCall.test.ts
- tests/foundry/LSP6KeyManager/LSP6SetDataTest.t.sol
Add extra parameter `address requestor` to function `lsp20VerifyCall`. This results in the following changes in interface IDs:
- LSP6: from `0xe7424397` to `0x23f34c62`.
- LSP20CallVerifier: from `0xc9dfc532` to `0x0d6ecac7`.
Update constants for the `bytes4` LSP20 Returned Status.
From:
```
VERIFY_CALL: {
// bytes3(keccak256("lsp20VerifyCall(address,address,uint256,bytes)")) + "0x00"
NO_POST_VERIFICATION: '0x1a238000',
// bytes3(keccak256("lsp20VerifyCall(address,address,uint256,bytes)")) + "0x01"
WITH_POST_VERIFICATION: '0x1a238001',
},
```
To:
```
VERIFY_CALL: {
// bytes3(keccak256("lsp20VerifyCall(address,address,address,uint256,bytes)")) + "0x00"
NO_POST_VERIFICATION: '0xde928f00',
// bytes3(keccak256("lsp20VerifyCall(address,address,address,uint256,bytes)")) + "0x01" …
```
> refactor!: add extra parameter `requestor` to `lsp20VerifyCall`

- CHANGELOG.md
- package-lock.json
- package.json
Prepare release candidate `0.12.0-rc.0`
- Bump version in `package.json`
- Add details in `CHANGELOG.md`
> chore: prepare release v0.12.0-rc.0

- tests/LSP6KeyManager/LSP6KeyManagerInit.test.ts
- tests/LSP7DigitalAsset/proxy/LSP7MintableInit.test.ts
- tests/LSP8IdentifiableDigitalAsset/proxy/LSP8MintableInit.test.ts
- tests/LSP9Vault/LSP9VaultInit.test.ts
- tests/UniversalProfileInit.test.ts
Add extra sanity checks when deploying base contracts.
> test: check that base contracts are initialized with `address(0)` as `owner()` and `target()`

- constants.ts
- contracts/LSP8IdentifiableDigitalAsset/LSP8Constants.sol
- foundry.toml
The data keys related to LSP8 are not up to date in the `.sol` files + are not present in `constants.ts`.
Update to the right values from LSP8 specs in the Solidity files and add them in the `constants.ts` file.
> refactor!: update LS8 Metadata keys to new LSP8 standard specs

- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- contracts/LSP6KeyManager/LSP6Modules/LSP6SetDataModule.sol
- contracts/Mocks/Reentrancy/LSP20ReentrantContractBatch.sol
- docs/contracts/LSP6KeyManager/LSP6KeyManager.md
- tests/LSP20CallVerification/LSP6/Interactions/ERC725XExecuteBatch.test.ts
- tests/LSP20CallVerification/LSP6/LSP20WithLSP6.behaviour.ts
- tests/LSP20CallVerification/LSP6/index.ts
- tests/LSP6KeyManager/Interactions/BatchExecute.test.ts
- tests/Reentrancy/LSP20/ERC725XExecuteToERC725XBatchExecute.test.ts
- tests/Reentrancy/LSP20/LSP20WithLSP6Reentrancy.test.ts
This PR Introduces the verification for the path`ERC725X.executeBatch` in the LSP6 Key Manager.
> feat!: Allows `ERC725X.executeBatch` path in LSP6 Key Manager

- contracts/LSP20CallVerification/LSP20CallVerification.sol
- contracts/LSP20CallVerification/LSP20Errors.sol
- docs/contracts/LSP0ERC725Account/LSP0ERC725Account.md
- docs/contracts/LSP20CallVerification/LSP20CallVerification.md
- docs/contracts/UniversalProfile.md
- tests/LSP20CallVerification/LSP20CallVerification.behaviour.ts
Cherry picking the following commits from #744 :
180acccbe0110f8d80666f582dab96f5e3f4d894
495c4e69e2cc4a87c3c6773201d724d23332963c
548fbecd8323ccaba9330885cccc232ebdf4998c
> perf: use `try / catch` in LSP20 verification to optimise gas cost

- contracts/LSP6KeyManager/LSP6Modules/LSP6SetDataModule.sol
- tests/LSP20CallVerification/LSP6/Admin/PermissionChangeAddExtensions.test.ts
- tests/LSP6KeyManager/Admin/PermissionChangeAddExtensions.test.ts
- allow setting 21 bytes under LSP17Extension data key in LSP6KeyManager
> fix: [M-03] allow setting 21 bytes under LSP17Extension data key in LSP6KeyManager

- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- tests/LSP17ContractExtension/LSP17Extendable.behaviour.ts
Prevent casting LSP17 Data shorter than 20 bytes.
In this way, if some mistake happens while setting the extension, the call won't be forwarded to the faulty casted extension.
> refactor: Prevent casting LSP17 Data shorter than 20 bytes

- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP14Ownable2Step/LSP14Ownable2Step.sol
- contracts/LSP1UniversalReceiver/LSP1Utils.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721InitAbstract.sol
- contracts/LSP9Vault/LSP9Vault.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- contracts/LSP9Vault/LSP9VaultInitAbstract.sol
- docs/libraries/LSP1UniversalReceiver/LSP1Utils.md
The function in LSP1Utils is named `tryNotifiyUniversalReceiver`. The name is a bit weird and misleading, as it might give the assumption that the function does a `try catch`, while it doesn't and simply call the `universalReceiver` function and bubbles up whatever error occurs during the external call.
Change the name of the function to `notifyUniversalReceiver` to make the code more readable.
> refactor: shorten LSP1Utils function to `notifyUniversalReceiver`

- contracts/LSP14Ownable2Step/LSP14Ownable2Step.sol
- tests/foundry/LSP14Ownable2Step/AcceptOwnershipCleanState.sol
> From Milo's report
Ownership of LSP0 accounts are transferred through a two-step process.
First, the owner calls [transferOwnership()](https://github.com/lukso-network/lsp-smart-contracts/blob/0c1738619818bcf2e01636f31782886b26fb91d7/contracts/LSP14Ownable2Step/LSP14Ownable2Step.sol#L84-L107) to nominate a pendingOwner:
[LSP14Ownable2Step.sol#L165-L166](https://github.com/lukso-network/lsp-smart-contracts/blob/0c1738619818bcf2e01636f31782886b26fb91d7/contracts/LSP14Ownable2Step/LSP14Ownable2Step.sol#L165-L166)
_pendingOwner = newOwner;
delete _renounceOwnershipStartedAt;
Afterwards, the pending owner calls [acceptOwnership()](https://github.com/lukso-network/lsp-smart-contracts/blob/0c1738619818bcf2e01636f31782886b26fb91d7/contracts/LSP14Ownable2Step/LSP14Ownable2Step.sol#L109-L128) to …
> fix: [M-02] reset `_renounceOwnershipStartedAt` on `acceptOwnership(..)` in LSP14

- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/Mocks/LSP20Owners/OwnerWIthURD.sol
- tests/LSP20CallVerification/LSP20CallVerification.behaviour.ts
- tests/UniversalProfile.behaviour.ts
This PR allows notifying the owner when ownership is renounced on owner call.
> refactor: [M-05] notify owner via LSP1 when confirming `renounceOwnership`

- contracts/LSP6KeyManager/LSP6Modules/LSP6ExecuteModule.sol
- contracts/Mocks/KeyManager/KeyManagerInternalsTester.sol
- docs/contracts/LSP6KeyManager/LSP6KeyManager.md
- foundry.toml
- tests/LSP6KeyManager/Interactions/PermissionTransferValue.test.ts
- tests/foundry/LSP6KeyManager/LSP6AllowedCallsTest.t.sol
This PR allows `0x00000000` to be an allowed call and not be confused with an empty call.
> fix: [M-04 + L-02] improve empty call type checks for selector `0x00000000`

- deploy/001_deploy_universal_profile.ts
- deploy/002_deploy_key_manager.ts
- deploy/003_deploy_universal_receiver_delegate.ts
- deploy/005_deploy_universal_receiver_delegate_vault.ts
- deploy/006_deploy_base_universal_profile.ts
- deploy/007_deploy_base_key_manager.ts
- deploy/008_deploy_lsp7_mintable.ts
- deploy/009_deploy_lsp8_mintable.ts
- deploy/010_deploy_base_lsp7_mintable.ts
- deploy/011_deploy_base_lsp8_mintable.ts
- deploy/012_deploy_vault.ts
- deploy/013_deploy_base_vault.ts
> refactor: use gas estimate in deployements scripts

- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- docs/contracts/LSP0ERC725Account/LSP0ERC725Account.md
- docs/contracts/UniversalProfile.md
docs: Improve natspec for LSP0
> docs: Improve natspec for LSP0

- constants.ts
Move `verification` object to own type so it allow to import it by 3rd parties.
> feat: extract verification metadata

- contracts/LSP17Extensions/Extension4337.sol
- contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
- docs/contracts/LSP17Extensions/Extension4337.md
- docs/contracts/LSP6KeyManager/LSP6KeyManager.md
Docs pages generated by the latest Docusaurus 3 version cannot parse Markdown that contains characters like `<` or `{`.
This was the case in [docs.lukso.tech](https://docs.lukso.tech).
This problem occurs for the docs of the `4337Extension.sol` contract, where the Natspecs from the `validateUserOps` function are fetched from `IAccount.sol`. Fixes this by:
- re-writing the same Natspec comments in this contract
- encapsulate the special characters `<` between back ticks to fix the docusaurus build error.
- add extra note about permissions for this extension.
Also fix a small broken link in LSP6 Natspecs.
> docs: write manual Natspec docs for `4337Extension.sol` to fix Docusaurus build error

- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- contracts/Mocks/UniversalReceivers/UniversalReceiverDelegateTokenReentrant.sol
- docs/contracts/LSP7DigitalAsset/LSP7DigitalAsset.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7Burnable.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CappedSupply.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20Mintable.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7Mintable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Burnable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CappedSupply.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Enumerable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/presets/LSP8CompatibleERC721Mintable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/presets/LSP8Mintable.md
- tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP.behaviour.ts
- tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault.behaviour.ts
- tests/LSP7DigitalAsset/LSP7DigitalAsset.behaviour.ts
- tests/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.behaviour.ts
- add internal notification functions in LSP7 and LSP8 to be able to override them easily 
- Add `operator` as part of the `lsp1Data` in a case of notifying using LSP1 for LSP7 and LSP8
> refactor: add `operator` to the transfer notification functions in  LSP7 and LSP8

- contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
- contracts/LSP4DigitalAssetMetadata/LSP4DigitalAssetMetadata.sol
- contracts/LSP4DigitalAssetMetadata/LSP4DigitalAssetMetadataCore.sol
- contracts/LSP4DigitalAssetMetadata/LSP4DigitalAssetMetadataInitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetInitAbstract.sol
- contracts/LSP9Vault/LSP9VaultCore.sol
- docs/contracts/LSP0ERC725Account/LSP0ERC725Account.md
- docs/contracts/LSP4DigitalAssetMetadata/LSP4DigitalAssetMetadata.md
- docs/contracts/LSP7DigitalAsset/LSP7DigitalAsset.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7Burnable.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CappedSupply.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20Mintable.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7Mintable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.md
- docs/contracts/LSP8IdentifiableDigitalAsset/presets/LSP8CompatibleERC721Mintable.md
- docs/contracts/LSP9Vault/LSP9Vault.md
- docs/contracts/UniversalProfile.md
- tests/LSP20CallVerification/LSP20CallVerification.behaviour.ts
- tests/LSP4DigitalAssetMetadata/LSP4DigitalAssetMetadata.behaviour.ts
- tests/LSP9Vault/LSP9Vault.behaviour.ts
- tests/UniversalProfile.behaviour.ts
> refactor!: Emit full DataChanged Event in LSP0 and LSP7, LSP8

- tests/foundry/LSP6KeyManager/LSP6Utils.t.sol
Optimisation of our foundry tests so that. 
For modular operations with a power of 2 as the denominator, instead of using `uint8 fee0 = fee % 32`,  we can use the bitwise `AND` operation: `uint8 fee0 = fee & (32 - 1)`. More optimised
> tests: optimize foundry tests to use bit operation over modulo

- contracts/LSP3ProfileMetadata/LSP3Constants.sol
- contracts/LSP4DigitalAssetMetadata/LSP4Constants.sol
- contracts/LSP4DigitalAssetMetadata/LSP4DigitalAssetMetadata.sol
- contracts/LSP7DigitalAsset/LSP7DigitalAsset.sol
- contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.sol
- contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20InitAbstract.sol
- contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20Mintable.sol
- contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20MintableInit.sol
- contracts/LSP7DigitalAsset/presets/LSP7Mintable.sol
- contracts/LSP7DigitalAsset/presets/LSP7MintableInit.sol
- contracts/LSP7DigitalAsset/presets/LSP7MintableInitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetInitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.sol
- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721InitAbstract.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8CompatibleERC721Mintable.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8CompatibleERC721MintableInit.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8Mintable.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8MintableInit.sol
- contracts/LSP8IdentifiableDigitalAsset/presets/LSP8MintableInitAbstract.sol
- docs/contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20Mintable.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7Mintable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/presets/LSP8CompatibleERC721Mintable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/presets/LSP8Mintable.md
Fix incorrect comments across the code for:
> docs: fix incorrect Natspec comments

- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
When running slither on contracts that inherit `LSP8IdentifiableDigitalAssetCore`, the following detector information warning is flagged.
This was introduced, probably by mistake in the following old PR.
https://github.com/lukso-network/lsp-smart-contracts/pull/278/files#diff-6bf798baf12f747ced625661057bfe96098e44a49c261fc80bf1977038f45260
This PR removes this old unused state variable.
> fix: remove unused state variable in LSP8

- contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Burnable.sol
chore: add `virtual` keyword in burn() in LSP8Burnable
> chore: [L-02] Missing virtual keyword on burn() in LSP8Burnable.sol

- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- tests/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.behaviour.ts
- add array length check for getDataBatchForTokenIds in LSP8
- add tests for array length check for getDataBatchForTokenIds in LSP8
> refactor: [L-05] tokenIds and dataKeys can have different lengths in getDataBatchForTokenIds()

- contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
- docs/contracts/LSP7DigitalAsset/LSP7DigitalAsset.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7Burnable.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CappedSupply.md
- docs/contracts/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7CompatibleERC20Mintable.md
- docs/contracts/LSP7DigitalAsset/presets/LSP7Mintable.md
- Advise use of increase/decrease allowance in LSP7
- Generate docs
> docs: [L-06] revokeOperator() does not protect against the double-spending allowance attack

- .github/workflows/benchmark.yml
This PR updates the GitHub Actions workflow event trigger from `pull_request` to `pull_request_target`. Below are the key differences and reasons for this change:
- **Context of Execution**:
- `pull_request`: The workflow runs in the context of the pull request itself, meaning it uses the code from the feature branch of the fork.
- `pull_request_target`: The workflow runs in the context of the base repository, using the code from the base branch to which the PR is targeted.
- **Access to Secrets**:
- `pull_request`: Has limited access to secrets, particularly when the PR is from a forked repository. This is a security measure to prevent exposing secrets to potentially unsafe code in forks.
- `pull_request_target`: Has access to all secrets of the base repository, even for PRs from forks. …
> ci: change event triggers for benchmark CI to include forks

- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
> fix: [L-08] add existence check before the _beforeTokenTransfer hook

- contracts/LSP8IdentifiableDigitalAsset/LSP8Errors.sol
- contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
- contracts/Mocks/Tokens/LSP8TransferOwnerChange.sol
- docs/contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Burnable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CappedSupply.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.md
- docs/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8Enumerable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/presets/LSP8CompatibleERC721Mintable.md
- docs/contracts/LSP8IdentifiableDigitalAsset/presets/LSP8Mintable.md
- tests/LSP8IdentifiableDigitalAsset/LSP8Mintable.behaviour.ts
> fix: [L-09] restrict owner change in _beforeTokenTransfer

- contracts/LSP16UniversalFactory/README.md
- Update the reference commit in LSP16UniversalFactory.md 
- Rename LSP16UniversalFactory.md to README.md so it display directly on file opening
> docs: Update and rename LSP16UniversalFactory.md to README.md

- .github/workflows/build-lint-test.yml
This is necessary for the typechain types of #857 to pass.
> ci: cache Typescript `types/` of packages in CI

- .github/workflows/release.yml
- .npmrc
- config/tsconfig/package.json
- packages/lsp-smart-contracts/scripts/ci/README.md
Related to the following issues and solutions:
- https://github.com/github/vscode-github-actions/issues/222#issuecomment-1765301497
- https://github.com/github/vscode-github-actions/issues/222#issuecomment-1741993145
And adding the `.npmrc` file from Github docs:
- https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
> ci: add `.npmrc` config file + setup `publish` as environnment to access `NPM_PUBLISH_TOKEN` via npm publish

- packages/lsp8-contracts/contracts/ILSP8IdentifiableDigitalAsset.sol
The Natspec comments description of the function `tokenOwnerOf` is incorrect and is a duplicate of `tokenIdsOf` in the `ILSP8` interface. Fix the comment with a correct one.
> docs: fix incorrect Natspec for LSP8 function `tokenOwnerOf`

- packages/lsp8-contracts/contracts/LSP8IdentifiableDigitalAssetCore.sol
- Use new data location for LSP8 tokenId data
> refactor: Use new data location for LSP8 tokenId data

- .github/workflows/deploy-verify.yml
- deploy/007_deploy_base_key_manager.ts
- packages/lsp-smart-contracts/hardhat.config.ts
> ci: use `tags` from hardhat deploy plugin to simplify deploy + verify workflow

- packages/lsp26-contracts/contracts/mock/InfiniteLoopURD.sol
- packages/lsp26-contracts/contracts/mock/ReturnBomb.sol
- packages/lsp26-contracts/contracts/mock/SelfDestructOnInterfaceCheck.sol
- packages/lsp26-contracts/tests/LSP26FollowerSystem.test.ts
Add tests:
- Make sure follow/unfollow cannot be reverted by return bomb attack
- Make sure follow/unfollow cannot be reverted by an infinite loop
- Make sure follow/unfollow cannot be reverted when contract self destructs on interface check
> test: add extreme case tests

- .github/workflows/benchmark.yml
- .github/workflows/build-lint-test.yml
- .github/workflows/coverage.yml
- .github/workflows/deploy-verify.yml
- .github/workflows/mythx-analysis.yml
- .github/workflows/solc_version.yml
- .tool-versions
Currently the project will not work on a machine with mise or asdf
due to the fact that the .tool-versions points to node 16.x which is no
longer compatible with most of the npm modules.
Along the way I also found that a lot of the github actions were still using
the old actions/setup-node@v2 and actions/setup-node@v3 as well
as specifying node 16.x
> fix: Match node versions across dev, github actions so it works with mise, asdf and so on

- packages/lsp-smart-contracts/tests/LSP7DigitalAsset/LSP7DigitalAsset.behaviour.ts
- packages/lsp7-contracts/contracts/LSP7DigitalAssetCore.sol
- disallow arbitrary sending of 0 amount in LSP7
New behavior: token owners and operators are allowed to send 0 as amount. Non operator or non token owner cannot send 0 as amount.
> fix: disallow arbitrary sending of 0 amount in LSP7

- packages/lsp-smart-contracts/contracts/Mocks/Tokens/LSP8TransferOwnerChange.sol
- packages/lsp7-contracts/contracts/LSP7DigitalAsset.sol
- packages/lsp7-contracts/contracts/LSP7DigitalAssetInitAbstract.sol
- packages/lsp8-contracts/contracts/LSP8IdentifiableDigitalAsset.sol
- packages/lsp8-contracts/contracts/LSP8IdentifiableDigitalAssetInitAbstract.sol
- packages/lsp8-contracts/contracts/extensions/LSP8Enumerable.sol
- packages/lsp8-contracts/contracts/extensions/LSP8EnumerableInitAbstract.sol
- packages/lsp8-contracts/contracts/extensions/LSP8Votes.sol
- packages/lsp8-contracts/contracts/extensions/LSP8VotesInitAbstract.sol
> feat: add force params to internal functions

- package-lock.json
- packages/lsp7-contracts/package.json
- packages/lsp8-contracts/package.json
- Fix `package-lock.json` corrupted (after removing the version field from the root `package.json`) by re-generating it.
- Remove dependencies on `@erc725/smart-contracts` in LSP7 and LSP8 package to avoid confusion (ERC725 package is not used directly in LSP7/8 packages, but rather inherited as `@erc725/smart-contracts-v8` from the LSP4 dependency).
> build: fix package-lock and remove `@erc725` in LSP7/8 package as already obtained from LSP4 package

- packages/lsp-smart-contracts/package.json
- packages/lsp-smart-contracts/tests/foundry/LSP20SetDataTest.t.sol
- packages/lsp11-contracts/package.json
- packages/lsp16-contracts/package.json
- packages/lsp2-contracts/foundry/LSP2Utils.t.sol
- packages/lsp2-contracts/package.json
- packages/lsp6-contracts/foundry/LSP6AllowedCallsTest.t.sol
- packages/lsp6-contracts/foundry/LSP6Permissions.t.sol
- packages/lsp6-contracts/foundry/LSP6SetDataTest.t.sol
- packages/lsp6-contracts/package.json
- packages/lsp7-contracts/contracts/LSP7DigitalAssetInitAbstract.sol
- template/package.json
`LSP7DigitalAssetInitAbstract` inherits `LSP17Extendable`:
```solidity
abstract contract LSP7DigitalAssetInitAbstract is
ILSP7DigitalAsset,
LSP4DigitalAssetMetadataInitAbstract,
LSP17Extendable
{
```
However, it should inherit `LSP17ExtendableInitAbstract` instead as it is an initializable contract.
> fix: use correct contract `LSP17ExtendableInitAbstract` in inheritance of LSP7 Init

- packages/lsp-smart-contracts/tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP.behaviour.ts
- packages/lsp-smart-contracts/tests/LSP7DigitalAsset/LSP7DigitalAsset.behaviour.ts
- packages/lsp-smart-contracts/tests/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAsset.behaviour.ts
- packages/lsp-smart-contracts/tests/LSP9Vault/LSP9Vault.behaviour.ts
By missing the `.to.be.true` in the chai tests, we discovered that the issue addressed in PR #1008 actually fixed an interface ID check that was not passing. 
The incorrect inheritance of inheriting `LSP17Extendable` ❌ instead of `LSP7ExtendableInitAbstract` ✅ resulted in returning `false` when calling `supportsInterface(ERC725Y interface ID)`. See the tests output below when using the `.to.be.true` at commit [`b71b532`](https://github.com/lukso-network/lsp-smart-contracts/commits/main/)
> test: adjust tests for support interface to assert with `to.be.true`

- packages/lsp7-contracts/contracts/ILSP7DigitalAsset.sol
Zero value transfers are known to be used for phishing attacks. Document that in Natspec comments of the LSP7 function. See these articles for rationale:
- https://cryptorank.io/news/feed/3ff47-180067-zero-value-token-transfer-phishing
- https://tokenview.medium.com/understanding-zero-transferfrom-scams-and-using-tokenview-explorer-to-identify-them-889e1b9f4e7c
- https://www.coinbase.com/en-de/blog/zero-transfer-phishing-part-1-attack-analysis
> docs: add info note in Natspec about zero transfer amounts from non operators

- packages/lsp7-contracts/README.md
- packages/lsp7-contracts/contracts/extensions/LSP7Votes.sol
- packages/lsp7-contracts/contracts/extensions/LSP7VotesInitAbstract.sol
- packages/lsp8-contracts/README.md
- packages/lsp8-contracts/contracts/extensions/LSP8Votes.sol
- packages/lsp8-contracts/contracts/extensions/LSP8VotesInitAbstract.sol
The `LSP7Votes` and `LSP8Votes` extension contracts have never gone through an audit. Add small notice in Natspec comment + README of these two packages to warn users if used.
> docs: add security audit note about token votes extensions

- packages/lsp-smart-contracts/package.json
> Keeping open as draft. Need to update after latest patch release that fixes the typed ABIs missing in the build + audit fix on LSP7. Will merge and include within v0.17.0 (Need to change the conventional commit prefix probably)
> fix: upgrade minimum dependencies in `@lukso/lsp-smart-contracts` to include security + build patch
